// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"sort"
	"text/template"

	"golang.org/x/tools/go/packages"
)

const boilerplate = `// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-integration; DO NOT EDIT.`

var tmpl = template.Must(template.New("").Parse(boilerplate + `

package main

import (
{{- range .}}
	_ "{{.}}"
{{- end}}
)
`))

func main() {
	flag.Parse()
	pkgs, err := packages.Load(&packages.Config{Mode: packages.NeedName}, flag.Args()...)
	if err != nil {
		fmt.Printf("load: %v\n", err)
		os.Exit(1)
	}

	var paths []string
	for _, p := range pkgs {
		if len(p.Errors) == 0 {
			paths = append(paths, p.PkgPath)
		}
	}
	sort.Strings(paths)

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, paths); err != nil {
		fmt.Printf("template: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile("integrations_gen.go", buf.Bytes(), 0644); err != nil {
		fmt.Printf("write: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("wrote integrations_gen.go\n")
}
