// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-options; DO NOT EDIT.

package options

// Children implements ChildValidator for APIOptions.
// Returns all non-nil option fields.
func (o *APIOptions) Children() []any {
	var children []any
	if o.Timeout != nil {
		children = append(children, o.Timeout)
	}
	if o.Serdes != nil {
		children = append(children, o.Serdes)
	}
	return children
}

// Children implements ChildValidator for AlterTableOptions.
// Returns all non-nil option fields.
func (o *AlterTableOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for AlterTypeOptions.
// Returns all non-nil option fields.
func (o *AlterTypeOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionCountDocumentsOptions.
// Returns all non-nil option fields.
func (o *CollectionCountDocumentsOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionDeleteManyOptions.
// Returns all non-nil option fields.
func (o *CollectionDeleteManyOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionDeleteOneOptions.
// Returns all non-nil option fields.
func (o *CollectionDeleteOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionEstimatedDocumentCountOptions.
// Returns all non-nil option fields.
func (o *CollectionEstimatedDocumentCountOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindAndRerankOptions.
// Returns all non-nil option fields.
func (o *CollectionFindAndRerankOptions) Children() []any {
	var children []any
	if o.Rerank != nil {
		children = append(children, o.Rerank)
	}
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOneAndDeleteOptions.
// Returns all non-nil option fields.
func (o *CollectionFindOneAndDeleteOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOneAndReplaceOptions.
// Returns all non-nil option fields.
func (o *CollectionFindOneAndReplaceOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOneAndUpdateOptions.
// Returns all non-nil option fields.
func (o *CollectionFindOneAndUpdateOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOneOptions.
// Returns all non-nil option fields.
func (o *CollectionFindOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOptions.
// Returns all non-nil option fields.
func (o *CollectionFindOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionInsertManyOptions.
// Returns all non-nil option fields.
func (o *CollectionInsertManyOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionInsertOneOptions.
// Returns all non-nil option fields.
func (o *CollectionInsertOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionOptionsOptions.
// Returns all non-nil option fields.
func (o *CollectionOptionsOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionReplaceOneOptions.
// Returns all non-nil option fields.
func (o *CollectionReplaceOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionUpdateManyOptions.
// Returns all non-nil option fields.
func (o *CollectionUpdateManyOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionUpdateOneOptions.
// Returns all non-nil option fields.
func (o *CollectionUpdateOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateCollectionOptions.
// Returns all non-nil option fields.
func (o *CreateCollectionOptions) Children() []any {
	var children []any
	if o.DefaultId != nil {
		children = append(children, o.DefaultId)
	}
	if o.Vector != nil {
		children = append(children, o.Vector)
	}
	if o.Indexing != nil {
		children = append(children, o.Indexing)
	}
	if o.Lexical != nil {
		children = append(children, o.Lexical)
	}
	if o.Rerank != nil {
		children = append(children, o.Rerank)
	}
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateDatabaseOptions.
// Returns all non-nil option fields.
func (o *CreateDatabaseOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateIndexOptions.
// Returns all non-nil option fields.
func (o *CreateIndexOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateKeyspaceOptions.
// Returns all non-nil option fields.
func (o *CreateKeyspaceOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateTableOptions.
// Returns all non-nil option fields.
func (o *CreateTableOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateTextIndexOptions.
// Returns all non-nil option fields.
func (o *CreateTextIndexOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateTypeOptions.
// Returns all non-nil option fields.
func (o *CreateTypeOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateVectorIndexOptions.
// Returns all non-nil option fields.
func (o *CreateVectorIndexOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for DatabaseInfoOptions.
// Returns all non-nil option fields.
func (o *DatabaseInfoOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for DropCollectionOptions.
// Returns all non-nil option fields.
func (o *DropCollectionOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for DropDatabaseOptions.
// Returns all non-nil option fields.
func (o *DropDatabaseOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for DropKeyspaceOptions.
// Returns all non-nil option fields.
func (o *DropKeyspaceOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for DropTableIndexOptions.
// Returns all non-nil option fields.
func (o *DropTableIndexOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for DropTableOptions.
// Returns all non-nil option fields.
func (o *DropTableOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for DropTypeOptions.
// Returns all non-nil option fields.
func (o *DropTypeOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for FindAvailableRegionsOptions.
// Returns all non-nil option fields.
func (o *FindAvailableRegionsOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for FindEmbeddingProvidersOptions.
// Returns all non-nil option fields.
func (o *FindEmbeddingProvidersOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for GetCollectionOptions.
// Returns all non-nil option fields.
func (o *GetCollectionOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for GetTableOptions.
// Returns all non-nil option fields.
func (o *GetTableOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for ListCollectionsOptions.
// Returns all non-nil option fields.
func (o *ListCollectionsOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for ListDatabasesOptions.
// Returns all non-nil option fields.
func (o *ListDatabasesOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for ListIndexesOptions.
// Returns all non-nil option fields.
func (o *ListIndexesOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for ListKeyspacesOptions.
// Returns all non-nil option fields.
func (o *ListKeyspacesOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for ListPCUGroupsOptions.
// Returns all non-nil option fields.
func (o *ListPCUGroupsOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for ListTablesOptions.
// Returns all non-nil option fields.
func (o *ListTablesOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for ListTypesOptions.
// Returns all non-nil option fields.
func (o *ListTypesOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for RerankOptions.
// Returns all non-nil option fields.
func (o *RerankOptions) Children() []any {
	var children []any
	if o.Service != nil {
		children = append(children, o.Service)
	}
	return children
}

// Children implements ChildValidator for TableDefinitionOptions.
// Returns all non-nil option fields.
func (o *TableDefinitionOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for TableDeleteManyOptions.
// Returns all non-nil option fields.
func (o *TableDeleteManyOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for TableDeleteOneOptions.
// Returns all non-nil option fields.
func (o *TableDeleteOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for TableFindOneOptions.
// Returns all non-nil option fields.
func (o *TableFindOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for TableFindOptions.
// Returns all non-nil option fields.
func (o *TableFindOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for TableInsertManyOptions.
// Returns all non-nil option fields.
func (o *TableInsertManyOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for TableInsertOneOptions.
// Returns all non-nil option fields.
func (o *TableInsertOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for TableUpdateOneOptions.
// Returns all non-nil option fields.
func (o *TableUpdateOneOptions) Children() []any {
	var children []any
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for VectorOptions.
// Returns all non-nil option fields.
func (o *VectorOptions) Children() []any {
	var children []any
	if o.Service != nil {
		children = append(children, o.Service)
	}
	return children
}
