package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
)

const boilerplate = `// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-options; DO NOT EDIT.`

var encoderTmpl = template.Must(template.New("").Funcs(template.FuncMap{"Title": title}).Parse(boilerplate + `
package serdes

import (
	"fmt"
	"reflect"
	"strconv"
	"unsafe"
	"math"
)

const MaxUintptr = ^uintptr(0)

func init() {
{{range .}}
kindCodecs[reflect.{{.Type | Title}}] = codec{encode{{.Type | Title}}Kind, decode{{.Type | Title}}Kind}
{{end}}
}

{{range .}}
func encode{{.Type | Title}}Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.{{.SerFunc}}(dst, {{.Cast}}(*(*{{.Type}})(p)){{.Args}}), nil
}

func decode{{.Type | Title}}Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := {{.DesFunc}}(src)
	if err != nil {
		return src, err
	}

	if {{.BoundsCheck}} {
		return src, fmt.Errorf("value %v out of range for {{.Type}}", num)
	}

	*(*{{.Type}})(p) = {{.Type}}(num)
	return src, nil
}
{{end}}`))

func main() {
	type spec struct{ Type, Cast, SerFunc, DesFunc, BoundsCheck, Args string }

	var specs []spec
	for _, t := range []string{"int", "int8", "int16", "int32", "int64"} {
		specs = append(specs, spec{
			Type:        t,
			Cast:        "int64",
			SerFunc:     "AppendInt",
			DesFunc:     "decodeInt",
			BoundsCheck: fmt.Sprintf("num < math.Min%s || num > math.Max%s", title(t), title(t)),
			Args:        ", 10",
		})
	}

	for _, t := range []string{"uint", "uint8", "uint16", "uint32", "uint64"} {
		specs = append(specs, spec{
			Type:        t,
			Cast:        "uint64",
			SerFunc:     "AppendUint",
			DesFunc:     "decodeUint",
			BoundsCheck: fmt.Sprintf("num < 0 || num > math.Max%s", title(t)),
			Args:        ", 10",
		})
	}

	specs = append(specs, spec{
		Type:        "uintptr",
		Cast:        "uint64",
		SerFunc:     "AppendUint",
		DesFunc:     "decodeUint",
		BoundsCheck: "num < 0 || num > uint64(MaxUintptr)",
		Args:        ", 10",
	})

	for _, t := range []int{32, 64} {
		specs = append(specs, spec{
			Type:        fmt.Sprintf("float%d", t),
			Cast:        "float64",
			SerFunc:     "AppendFloat",
			DesFunc:     "decodeFloat",
			BoundsCheck: "false",
			Args:        fmt.Sprintf(", 'g', -1, %d", t),
		})
	}

	var buf bytes.Buffer
	if err := encoderTmpl.Execute(&buf, specs); err != nil {
		panic(err)
	}

	if err := os.WriteFile("serdes_gen.go", buf.Bytes(), 0644); err != nil {
		panic(err)
	}

	fmt.Printf("wrote serdes_gen.go\n")
}

func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
