// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package main

import (
	"bytes"
	"fmt"
	"os"
	"strings"
	"text/template"
)

const boilerplate = `// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-options; DO NOT EDIT.`

var encoderTmpl = template.Must(template.New("").Funcs(template.FuncMap{"Title": title}).Parse(boilerplate + `
package serdes

import (
	"fmt"
	"math"
	"reflect"
	"strconv"
	"unsafe"
)

const maxUintptr = ^uintptr(0)

func init() {
{{range .}}
	kindCodecs[reflect.{{.Type | Title}}] = codec{{"{"}}{{.Type}}Encoder, {{.Type}}Decoder}
{{end}}
}
{{range .}}
func {{.Type}}Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
{{if .IsFloat}}	f := float64(*(*{{.Type}})(p))
	abs := math.Abs(f)
	fmtCh := byte('f')
	if abs != 0 {
		if {{.Type}}(abs) < 1e-6 || {{.Type}}(abs) >= 1e21 {
			fmtCh = 'e'
		}
	}
	dst = strconv.AppendFloat(dst, f, fmtCh, -1, {{.Bits}})
	if fmtCh == 'e' {
		n := len(dst)
		if n >= 4 && dst[n-4] == 'e' && dst[n-3] == '-' && dst[n-2] == '0' {
			dst[n-2] = dst[n-1]
			dst = dst[:n-1]
		}
	}
	return dst, nil
{{else}}	return strconv.{{.SerFunc}}(dst, {{.Cast}}(*(*{{.Type}})(p)), 10), nil
{{end}}}

func {{.Type}}Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	srcAfter, num, err := {{.DesFunc}}(ctx, src)
	if err != nil {
		return srcAfter, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[{{.Type}}](), err)
	}

	if {{.BoundsCheck}} {
		return srcAfter, ctx.unmarshalValueTypeError(src, reflect.TypeFor[{{.Type}}](), fmt.Sprintf("number %v", num))
	}

	*(*{{.Type}})(p) = {{.Type}}(num)
	return srcAfter, nil
}
{{end}}`))

func main() {
	type spec struct {
		Type, Cast, SerFunc, DesFunc, BoundsCheck string
		IsFloat                                   bool
		Bits                                      int
	}

	var specs []spec
	for _, t := range []string{"int", "int8", "int16", "int32", "int64"} {
		specs = append(specs, spec{
			Type:        t,
			Cast:        "int64",
			SerFunc:     "AppendInt",
			DesFunc:     "parseInt",
			BoundsCheck: fmt.Sprintf("num < math.Min%s || num > math.Max%s", title(t), title(t)),
		})
	}

	for _, t := range []string{"uint", "uint8", "uint16", "uint32", "uint64"} {
		specs = append(specs, spec{
			Type:        t,
			Cast:        "uint64",
			SerFunc:     "AppendUint",
			DesFunc:     "parseUint",
			BoundsCheck: fmt.Sprintf("num < 0 || num > math.Max%s", title(t)),
		})
	}

	specs = append(specs, spec{
		Type:        "uintptr",
		Cast:        "uint64",
		SerFunc:     "AppendUint",
		DesFunc:     "parseUint",
		BoundsCheck: "num < 0 || num > uint64(maxUintptr)",
	})

	for _, t := range []int{32, 64} {
		specs = append(specs, spec{
			Type:        fmt.Sprintf("float%d", t),
			Cast:        "float64",
			DesFunc:     "parseFloat",
			BoundsCheck: "false",
			IsFloat:     true,
			Bits:        t,
		})
	}

	var buf bytes.Buffer
	if err := encoderTmpl.Execute(&buf, specs); err != nil {
		panic(err)
	}

	if err := os.WriteFile("serdes_gen.go", buf.Bytes(), 0644); err != nil {
		panic(err)
	}

	fmt.Printf("wrote serdes_gen.go\n")
}

func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
