// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-options; DO NOT EDIT.
package serdes

import (
	"fmt"
	"reflect"
	"strconv"
	"unsafe"
	"math"
)

const MaxUintptr = ^uintptr(0)

func init() {

    kindCodecs[reflect.Int] = codec{encodeIntKind, decodeIntKind}

    kindCodecs[reflect.Int8] = codec{encodeInt8Kind, decodeInt8Kind}

    kindCodecs[reflect.Int16] = codec{encodeInt16Kind, decodeInt16Kind}

    kindCodecs[reflect.Int32] = codec{encodeInt32Kind, decodeInt32Kind}

    kindCodecs[reflect.Int64] = codec{encodeInt64Kind, decodeInt64Kind}

    kindCodecs[reflect.Uint] = codec{encodeUintKind, decodeUintKind}

    kindCodecs[reflect.Uint8] = codec{encodeUint8Kind, decodeUint8Kind}

    kindCodecs[reflect.Uint16] = codec{encodeUint16Kind, decodeUint16Kind}

    kindCodecs[reflect.Uint32] = codec{encodeUint32Kind, decodeUint32Kind}

    kindCodecs[reflect.Uint64] = codec{encodeUint64Kind, decodeUint64Kind}

    kindCodecs[reflect.Uintptr] = codec{encodeUintptrKind, decodeUintptrKind}

    kindCodecs[reflect.Float32] = codec{encodeFloat32Kind, decodeFloat32Kind}

    kindCodecs[reflect.Float64] = codec{encodeFloat64Kind, decodeFloat64Kind}

}


func encodeIntKind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int)(p)), 10), nil
}

func decodeIntKind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(src)
	if err != nil {
		return src, err
	}

	if num < math.MinInt || num > math.MaxInt {
		return src, fmt.Errorf("value %v out of range for int", num)
	}

	*(*int)(p) = int(num)
	return src, nil
}

func encodeInt8Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int8)(p)), 10), nil
}

func decodeInt8Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(src)
	if err != nil {
		return src, err
	}

	if num < math.MinInt8 || num > math.MaxInt8 {
		return src, fmt.Errorf("value %v out of range for int8", num)
	}

	*(*int8)(p) = int8(num)
	return src, nil
}

func encodeInt16Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int16)(p)), 10), nil
}

func decodeInt16Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(src)
	if err != nil {
		return src, err
	}

	if num < math.MinInt16 || num > math.MaxInt16 {
		return src, fmt.Errorf("value %v out of range for int16", num)
	}

	*(*int16)(p) = int16(num)
	return src, nil
}

func encodeInt32Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int32)(p)), 10), nil
}

func decodeInt32Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(src)
	if err != nil {
		return src, err
	}

	if num < math.MinInt32 || num > math.MaxInt32 {
		return src, fmt.Errorf("value %v out of range for int32", num)
	}

	*(*int32)(p) = int32(num)
	return src, nil
}

func encodeInt64Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int64)(p)), 10), nil
}

func decodeInt64Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(src)
	if err != nil {
		return src, err
	}

	if num < math.MinInt64 || num > math.MaxInt64 {
		return src, fmt.Errorf("value %v out of range for int64", num)
	}

	*(*int64)(p) = int64(num)
	return src, nil
}

func encodeUintKind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint)(p)), 10), nil
}

func decodeUintKind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(src)
	if err != nil {
		return src, err
	}

	if num < 0 || num > math.MaxUint {
		return src, fmt.Errorf("value %v out of range for uint", num)
	}

	*(*uint)(p) = uint(num)
	return src, nil
}

func encodeUint8Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint8)(p)), 10), nil
}

func decodeUint8Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(src)
	if err != nil {
		return src, err
	}

	if num < 0 || num > math.MaxUint8 {
		return src, fmt.Errorf("value %v out of range for uint8", num)
	}

	*(*uint8)(p) = uint8(num)
	return src, nil
}

func encodeUint16Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint16)(p)), 10), nil
}

func decodeUint16Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(src)
	if err != nil {
		return src, err
	}

	if num < 0 || num > math.MaxUint16 {
		return src, fmt.Errorf("value %v out of range for uint16", num)
	}

	*(*uint16)(p) = uint16(num)
	return src, nil
}

func encodeUint32Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint32)(p)), 10), nil
}

func decodeUint32Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(src)
	if err != nil {
		return src, err
	}

	if num < 0 || num > math.MaxUint32 {
		return src, fmt.Errorf("value %v out of range for uint32", num)
	}

	*(*uint32)(p) = uint32(num)
	return src, nil
}

func encodeUint64Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint64)(p)), 10), nil
}

func decodeUint64Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(src)
	if err != nil {
		return src, err
	}

	if num < 0 || num > math.MaxUint64 {
		return src, fmt.Errorf("value %v out of range for uint64", num)
	}

	*(*uint64)(p) = uint64(num)
	return src, nil
}

func encodeUintptrKind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uintptr)(p)), 10), nil
}

func decodeUintptrKind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(src)
	if err != nil {
		return src, err
	}

	if num < 0 || num > uint64(MaxUintptr) {
		return src, fmt.Errorf("value %v out of range for uintptr", num)
	}

	*(*uintptr)(p) = uintptr(num)
	return src, nil
}

func encodeFloat32Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendFloat(dst, float64(*(*float32)(p)), 'g', -1, 32), nil
}

func decodeFloat32Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseFloat(src)
	if err != nil {
		return src, err
	}

	if false {
		return src, fmt.Errorf("value %v out of range for float32", num)
	}

	*(*float32)(p) = float32(num)
	return src, nil
}

func encodeFloat64Kind(_ encodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendFloat(dst, float64(*(*float64)(p)), 'g', -1, 64), nil
}

func decodeFloat64Kind(_ decodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseFloat(src)
	if err != nil {
		return src, err
	}

	if false {
		return src, fmt.Errorf("value %v out of range for float64", num)
	}

	*(*float64)(p) = float64(num)
	return src, nil
}
