// Copyright DataStax, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-options; DO NOT EDIT.

package options

import (
	"net/http"
	"time"
)

// Setters implements Builder[APIOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[APIOptions].
func (o *APIOptions) Setters() []func(*APIOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for APIOptions.
func (o *APIOptions) Validate() error { return nil }

// aPIOptionsBuilder is a builder for APIOptions.
type aPIOptionsBuilder struct {
	setters []func(*APIOptions)
}

// API creates a new builder for APIOptions.
func API() *aPIOptionsBuilder {
	return &aPIOptionsBuilder{}
}

// Setters implements Builder[APIOptions].
func (b *aPIOptionsBuilder) Setters() []func(*APIOptions) {
	return b.setters
}

// SetToken sets the Token option.
// Token is the authentication token for Astra DB
func (b *aPIOptionsBuilder) SetToken(v string) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) { o.Token = &v })
	return b
}

// SetKeyspace sets the Keyspace option.
// Keyspace is the keyspace to use for operations
func (b *aPIOptionsBuilder) SetKeyspace(v string) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) { o.Keyspace = &v })
	return b
}

// SetAPIVersion sets the APIVersion option.
// APIVersion is the Data API version (e.g., "v1")
func (b *aPIOptionsBuilder) SetAPIVersion(v string) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) { o.APIVersion = &v })
	return b
}

// SetHTTPClient sets the HTTPClient option.
// HTTPClient is the HTTP client to use for requests
func (b *aPIOptionsBuilder) SetHTTPClient(v http.Client) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) { o.HTTPClient = &v })
	return b
}

// SetHeaders sets the Headers option.
// Headers contains custom headers to include in requests
// (e.g., for embedding API keys like "x-embedding-api-key")
func (b *aPIOptionsBuilder) SetHeaders(v map[string]string) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) { o.Headers = v })
	return b
}

// SetTimeout sets the Timeout option.
// Timeout contains timeout configuration
func (b *aPIOptionsBuilder) SetTimeout(v ...Builder[TimeoutOptions]) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) {
		o.Timeout = Merge(v...)
	})
	return b
}

// SetSerdes sets the Serdes option.
// Serdes contains serialization/deserialization options
func (b *aPIOptionsBuilder) SetSerdes(v ...Builder[SerdesOptions]) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) {
		o.Serdes = Merge(v...)
	})
	return b
}

// SetAstraEnvironment sets the AstraEnvironment option.
// AstraEnvironment is the Astra environment (prod, dev, test).
// Controls the DevOps API URL. Defaults to prod.
func (b *aPIOptionsBuilder) SetAstraEnvironment(v AstraEnvironment) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) { o.AstraEnvironment = &v })
	return b
}

// SetDataAPIBackend sets the DataAPIBackend option.
// DataAPIBackend is the database backend (astra, hcd, dse, cassandra, other).
// Controls the Data API path. Defaults to astra.
func (b *aPIOptionsBuilder) SetDataAPIBackend(v DataAPIBackend) *aPIOptionsBuilder {
	b.setters = append(b.setters, func(o *APIOptions) { o.DataAPIBackend = &v })
	return b
}

// CollectionDefaultIdOption is a convenience alias for Builder[CollectionDefaultIdOptions].
type CollectionDefaultIdOption = Builder[CollectionDefaultIdOptions]

// Setters implements Builder[CollectionDefaultIdOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CollectionDefaultIdOptions].
func (o *CollectionDefaultIdOptions) Setters() []func(*CollectionDefaultIdOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CollectionDefaultIdOptions.
func (o *CollectionDefaultIdOptions) Validate() error { return nil }

// collectionDefaultIdOptionsBuilder is a builder for CollectionDefaultIdOptions.
type collectionDefaultIdOptionsBuilder struct {
	setters []func(*CollectionDefaultIdOptions)
}

// CollectionDefaultId creates a new builder for CollectionDefaultIdOptions.
func CollectionDefaultId() *collectionDefaultIdOptionsBuilder {
	return &collectionDefaultIdOptionsBuilder{}
}

// Setters implements Builder[CollectionDefaultIdOptions].
func (b *collectionDefaultIdOptionsBuilder) Setters() []func(*CollectionDefaultIdOptions) {
	return b.setters
}

// SetType sets the Type option.
// Type is the type of the default ID that the API should generate if no ID is provided in the inserted document.
// Valid values: "uuid", "uuidv6", "uuidv7", "objectId".
// If not specified, the default ID will be a string UUID.
func (b *collectionDefaultIdOptionsBuilder) SetType(v DefaultIdType) *collectionDefaultIdOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionDefaultIdOptions) { o.Type = &v })
	return b
}

// CollectionFindOption is a convenience alias for Builder[CollectionFindOptions].
type CollectionFindOption = Builder[CollectionFindOptions]

// Setters implements Builder[CollectionFindOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CollectionFindOptions].
func (o *CollectionFindOptions) Setters() []func(*CollectionFindOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CollectionFindOptions.
func (o *CollectionFindOptions) Validate() error { return nil }

// collectionFindOptionsBuilder is a builder for CollectionFindOptions.
type collectionFindOptionsBuilder struct {
	setters []func(*CollectionFindOptions)
}

// CollectionFind creates a new builder for CollectionFindOptions.
func CollectionFind() *collectionFindOptionsBuilder {
	return &collectionFindOptionsBuilder{}
}

// Setters implements Builder[CollectionFindOptions].
func (b *collectionFindOptionsBuilder) Setters() []func(*CollectionFindOptions) {
	return b.setters
}

// SetSort sets the Sort option.
// Sort specifies how to sort the results. Can be used for:
//   - Ascending/descending sort on fields (e.g., {"rating": 1, "title": -1})
//   - Vector search with a vector (e.g., {"$vector": [0.1, 0.2, 0.3]})
//   - Vector search with vectorize (e.g., {"$vectorize": "search text"})
func (b *collectionFindOptionsBuilder) SetSort(v map[string]any) *collectionFindOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionFindOptions) { o.Sort = v })
	return b
}

// SetProjection sets the Projection option.
// Projection controls which fields are included or excluded in the returned documents
// Use true to include a field, false to exclude it
func (b *collectionFindOptionsBuilder) SetProjection(v map[string]any) *collectionFindOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionFindOptions) { o.Projection = v })
	return b
}

// SetLimit sets the Limit option.
// Limit limits the total number of documents returned
func (b *collectionFindOptionsBuilder) SetLimit(v int) *collectionFindOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionFindOptions) { o.Limit = &v })
	return b
}

// SetSkip sets the Skip option.
// Skip specifies the number of documents to bypass before returning results.
// Only valid with ascending/descending sort, not with vector search.
func (b *collectionFindOptionsBuilder) SetSkip(v int) *collectionFindOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionFindOptions) { o.Skip = &v })
	return b
}

// SetIncludeSimilarity sets the IncludeSimilarity option.
// IncludeSimilarity if true, includes a $similarity property in the response
// for vector searches.
func (b *collectionFindOptionsBuilder) SetIncludeSimilarity(v bool) *collectionFindOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionFindOptions) { o.IncludeSimilarity = &v })
	return b
}

// SetIncludeSortVector sets the IncludeSortVector option.
// IncludeSortVector if true, includes the sort vector in the response.
// Useful for vector searches using $vectorize.
func (b *collectionFindOptionsBuilder) SetIncludeSortVector(v bool) *collectionFindOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionFindOptions) { o.IncludeSortVector = &v })
	return b
}

// SetInitialPageState sets the InitialPageState option.
// InitialPageState is used for pagination to fetch the next page of results
func (b *collectionFindOptionsBuilder) SetInitialPageState(v string) *collectionFindOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionFindOptions) { o.InitialPageState = &v })
	return b
}

// CollectionUpdateOneOption is a convenience alias for Builder[CollectionUpdateOneOptions].
type CollectionUpdateOneOption = Builder[CollectionUpdateOneOptions]

// Setters implements Builder[CollectionUpdateOneOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CollectionUpdateOneOptions].
func (o *CollectionUpdateOneOptions) Setters() []func(*CollectionUpdateOneOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CollectionUpdateOneOptions.
func (o *CollectionUpdateOneOptions) Validate() error { return nil }

// collectionUpdateOneOptionsBuilder is a builder for CollectionUpdateOneOptions.
type collectionUpdateOneOptionsBuilder struct {
	setters []func(*CollectionUpdateOneOptions)
}

// CollectionUpdateOne creates a new builder for CollectionUpdateOneOptions.
func CollectionUpdateOne() *collectionUpdateOneOptionsBuilder {
	return &collectionUpdateOneOptionsBuilder{}
}

// Setters implements Builder[CollectionUpdateOneOptions].
func (b *collectionUpdateOneOptionsBuilder) Setters() []func(*CollectionUpdateOneOptions) {
	return b.setters
}

// SetSort sets the Sort option.
// Sort specifies the sort order to apply before selecting the document to update.
// This determines which document is updated when the filter matches multiple documents.
func (b *collectionUpdateOneOptionsBuilder) SetSort(v map[string]any) *collectionUpdateOneOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionUpdateOneOptions) { o.Sort = v })
	return b
}

// SetUpsert sets the Upsert option.
// Upsert if true, inserts a new document if no document matches the filter.
func (b *collectionUpdateOneOptionsBuilder) SetUpsert(v bool) *collectionUpdateOneOptionsBuilder {
	b.setters = append(b.setters, func(o *CollectionUpdateOneOptions) { o.Upsert = &v })
	return b
}

// CreateCollectionOption is a convenience alias for Builder[CreateCollectionOptions].
type CreateCollectionOption = Builder[CreateCollectionOptions]

// Setters implements Builder[CreateCollectionOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateCollectionOptions].
func (o *CreateCollectionOptions) Setters() []func(*CreateCollectionOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateCollectionOptions.
func (o *CreateCollectionOptions) Validate() error { return nil }

// createCollectionOptionsBuilder is a builder for CreateCollectionOptions.
type createCollectionOptionsBuilder struct {
	setters []func(*CreateCollectionOptions)
}

// CreateCollection creates a new builder for CreateCollectionOptions.
func CreateCollection() *createCollectionOptionsBuilder {
	return &createCollectionOptionsBuilder{}
}

// Setters implements Builder[CreateCollectionOptions].
func (b *createCollectionOptionsBuilder) Setters() []func(*CreateCollectionOptions) {
	return b.setters
}

// SetDefaultId sets the DefaultId option.
// Settings for generating ids
func (b *createCollectionOptionsBuilder) SetDefaultId(v ...Builder[CollectionDefaultIdOptions]) *createCollectionOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateCollectionOptions) {
		o.DefaultId = Merge(v...)
	})
	return b
}

// SetVector sets the Vector option.
// Vector specifications for the collection
func (b *createCollectionOptionsBuilder) SetVector(v ...Builder[VectorOptions]) *createCollectionOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateCollectionOptions) {
		o.Vector = Merge(v...)
	})
	return b
}

// SetIndexing sets the Indexing option.
// Overrides for document indexing
func (b *createCollectionOptionsBuilder) SetIndexing(v ...Builder[IndexingOptions]) *createCollectionOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateCollectionOptions) {
		o.Indexing = Merge(v...)
	})
	return b
}

// SetLexical sets the Lexical option.
// Lexical analysis options for the collection
func (b *createCollectionOptionsBuilder) SetLexical(v ...Builder[LexicalOptions]) *createCollectionOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateCollectionOptions) {
		o.Lexical = Merge(v...)
	})
	return b
}

// SetRerank sets the Rerank option.
// Reranking options for the collection
func (b *createCollectionOptionsBuilder) SetRerank(v ...Builder[RerankOptions]) *createCollectionOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateCollectionOptions) {
		o.Rerank = Merge(v...)
	})
	return b
}

// CreateDatabaseOption is a convenience alias for Builder[CreateDatabaseOptions].
type CreateDatabaseOption = Builder[CreateDatabaseOptions]

// Setters implements Builder[CreateDatabaseOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateDatabaseOptions].
func (o *CreateDatabaseOptions) Setters() []func(*CreateDatabaseOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateDatabaseOptions.
func (o *CreateDatabaseOptions) Validate() error { return nil }

// createDatabaseOptionsBuilder is a builder for CreateDatabaseOptions.
type createDatabaseOptionsBuilder struct {
	setters []func(*CreateDatabaseOptions)
}

// CreateDatabase creates a new builder for CreateDatabaseOptions.
func CreateDatabase() *createDatabaseOptionsBuilder {
	return &createDatabaseOptionsBuilder{}
}

// Setters implements Builder[CreateDatabaseOptions].
func (b *createDatabaseOptionsBuilder) Setters() []func(*CreateDatabaseOptions) {
	return b.setters
}

// SetKeyspace sets the Keyspace option.
// Keyspace is the initial keyspace name. Defaults to "default_keyspace" if not specified.
func (b *createDatabaseOptionsBuilder) SetKeyspace(v string) *createDatabaseOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateDatabaseOptions) { o.Keyspace = &v })
	return b
}

// SetBlocking sets the Blocking option.
// Blocking controls whether to wait for the database to become ACTIVE.
// Defaults to true.
func (b *createDatabaseOptionsBuilder) SetBlocking(v bool) *createDatabaseOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateDatabaseOptions) { o.Blocking = &v })
	return b
}

// SetPollInterval sets the PollInterval option.
// PollInterval is how often to check the database status when blocking.
// Defaults to DefaultDatabasePollInterval (10 seconds).
func (b *createDatabaseOptionsBuilder) SetPollInterval(v time.Duration) *createDatabaseOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateDatabaseOptions) { o.PollInterval = &v })
	return b
}

// CreateIndexOption is a convenience alias for Builder[CreateIndexOptions].
type CreateIndexOption = Builder[CreateIndexOptions]

// Setters implements Builder[CreateIndexOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateIndexOptions].
func (o *CreateIndexOptions) Setters() []func(*CreateIndexOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateIndexOptions.
func (o *CreateIndexOptions) Validate() error { return nil }

// createIndexOptionsBuilder is a builder for CreateIndexOptions.
type createIndexOptionsBuilder struct {
	setters []func(*CreateIndexOptions)
}

// CreateIndex creates a new builder for CreateIndexOptions.
func CreateIndex() *createIndexOptionsBuilder {
	return &createIndexOptionsBuilder{}
}

// Setters implements Builder[CreateIndexOptions].
func (b *createIndexOptionsBuilder) Setters() []func(*CreateIndexOptions) {
	return b.setters
}

// SetIfNotExists sets the IfNotExists option.
// IfNotExists if true, the command will silently succeed even if an index
// with the given name already exists. This only checks index names, not definitions.
func (b *createIndexOptionsBuilder) SetIfNotExists(v bool) *createIndexOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateIndexOptions) { o.IfNotExists = &v })
	return b
}

// SetAscii sets the Ascii option.
// Ascii if true, converts non-ASCII characters to US-ASCII before indexing.
// Only applicable to text columns.
func (b *createIndexOptionsBuilder) SetAscii(v bool) *createIndexOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateIndexOptions) { o.Ascii = &v })
	return b
}

// SetNormalize sets the Normalize option.
// Normalize if true, applies Unicode character normalization before indexing.
// Only applicable to text columns.
func (b *createIndexOptionsBuilder) SetNormalize(v bool) *createIndexOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateIndexOptions) { o.Normalize = &v })
	return b
}

// SetCaseSensitive sets the CaseSensitive option.
// CaseSensitive if true (default), enforces case-sensitive matching.
// Only applicable to text columns.
func (b *createIndexOptionsBuilder) SetCaseSensitive(v bool) *createIndexOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateIndexOptions) { o.CaseSensitive = &v })
	return b
}

// CreateKeyspaceOption is a convenience alias for Builder[CreateKeyspaceOptions].
type CreateKeyspaceOption = Builder[CreateKeyspaceOptions]

// Setters implements Builder[CreateKeyspaceOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateKeyspaceOptions].
func (o *CreateKeyspaceOptions) Setters() []func(*CreateKeyspaceOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateKeyspaceOptions.
func (o *CreateKeyspaceOptions) Validate() error { return nil }

// createKeyspaceOptionsBuilder is a builder for CreateKeyspaceOptions.
type createKeyspaceOptionsBuilder struct {
	setters []func(*CreateKeyspaceOptions)
}

// CreateKeyspace creates a new builder for CreateKeyspaceOptions.
func CreateKeyspace() *createKeyspaceOptionsBuilder {
	return &createKeyspaceOptionsBuilder{}
}

// Setters implements Builder[CreateKeyspaceOptions].
func (b *createKeyspaceOptionsBuilder) Setters() []func(*CreateKeyspaceOptions) {
	return b.setters
}

// SetBlocking sets the Blocking option.
// Blocking controls whether to wait for the keyspace to become visible.
// Defaults to true. Only used by the Astra (DevOps API) path.
func (b *createKeyspaceOptionsBuilder) SetBlocking(v bool) *createKeyspaceOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateKeyspaceOptions) { o.Blocking = &v })
	return b
}

// SetPollInterval sets the PollInterval option.
// PollInterval is how often to check whether the keyspace exists when blocking.
// Defaults to DefaultKeyspacePollInterval (1 second). Only used by the Astra (DevOps API) path.
func (b *createKeyspaceOptionsBuilder) SetPollInterval(v time.Duration) *createKeyspaceOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateKeyspaceOptions) { o.PollInterval = &v })
	return b
}

// SetReplicationFactor sets the ReplicationFactor option.
// ReplicationFactor sets the replication factor for the keyspace.
// Only used by the Data API path (non-Astra environments).
func (b *createKeyspaceOptionsBuilder) SetReplicationFactor(v int) *createKeyspaceOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateKeyspaceOptions) { o.ReplicationFactor = &v })
	return b
}

// CreateTableOption is a convenience alias for Builder[CreateTableOptions].
type CreateTableOption = Builder[CreateTableOptions]

// Setters implements Builder[CreateTableOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateTableOptions].
func (o *CreateTableOptions) Setters() []func(*CreateTableOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateTableOptions.
func (o *CreateTableOptions) Validate() error { return nil }

// createTableOptionsBuilder is a builder for CreateTableOptions.
type createTableOptionsBuilder struct {
	setters []func(*CreateTableOptions)
}

// CreateTable creates a new builder for CreateTableOptions.
func CreateTable() *createTableOptionsBuilder {
	return &createTableOptionsBuilder{}
}

// Setters implements Builder[CreateTableOptions].
func (b *createTableOptionsBuilder) Setters() []func(*CreateTableOptions) {
	return b.setters
}

// SetIfNotExists sets the IfNotExists option.
// IfNotExists if true, the command will silently succeed even if a table
// with the given name already exists. This only checks table names, not schemas.
func (b *createTableOptionsBuilder) SetIfNotExists(v bool) *createTableOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateTableOptions) { o.IfNotExists = &v })
	return b
}

// SetKeyspace sets the Keyspace option.
// Keyspace specifies the keyspace in which to create the table.
// If not provided, defaults to the working keyspace for the database.
func (b *createTableOptionsBuilder) SetKeyspace(v string) *createTableOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateTableOptions) { o.Keyspace = &v })
	return b
}

// CreateVectorIndexOption is a convenience alias for Builder[CreateVectorIndexOptions].
type CreateVectorIndexOption = Builder[CreateVectorIndexOptions]

// Setters implements Builder[CreateVectorIndexOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateVectorIndexOptions].
func (o *CreateVectorIndexOptions) Setters() []func(*CreateVectorIndexOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateVectorIndexOptions.
func (o *CreateVectorIndexOptions) Validate() error { return nil }

// createVectorIndexOptionsBuilder is a builder for CreateVectorIndexOptions.
type createVectorIndexOptionsBuilder struct {
	setters []func(*CreateVectorIndexOptions)
}

// CreateVectorIndex creates a new builder for CreateVectorIndexOptions.
func CreateVectorIndex() *createVectorIndexOptionsBuilder {
	return &createVectorIndexOptionsBuilder{}
}

// Setters implements Builder[CreateVectorIndexOptions].
func (b *createVectorIndexOptionsBuilder) Setters() []func(*CreateVectorIndexOptions) {
	return b.setters
}

// SetIfNotExists sets the IfNotExists option.
// IfNotExists if true, the command will silently succeed even if an index
// with the given name already exists. This only checks index names, not definitions.
func (b *createVectorIndexOptionsBuilder) SetIfNotExists(v bool) *createVectorIndexOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateVectorIndexOptions) { o.IfNotExists = &v })
	return b
}

// SetMetric sets the Metric option.
// Metric is the similarity measurement for vector search.
// Valid values: "cosine" (default), "dot_product", "euclidean"
func (b *createVectorIndexOptionsBuilder) SetMetric(v VectorMetric) *createVectorIndexOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateVectorIndexOptions) { o.Metric = &v })
	return b
}

// SetSourceModel sets the SourceModel option.
// SourceModel is the embedding generation model, enabling optimizations.
// Valid values: "ada002", "bert", "cohere-v3", "gecko", "nv-qa-4",
// "openai-v3-large", "openai-v3-small", "other" (default)
//
// NOTE: following the other libraries' patterns, we are using a enum-like option for Metric, but
// this is a string. For reference:
// https://docs.datastax.com/en/astra-db-serverless/api-reference/table-index-methods/create-vector-index.html#parameters
func (b *createVectorIndexOptionsBuilder) SetSourceModel(v string) *createVectorIndexOptionsBuilder {
	b.setters = append(b.setters, func(o *CreateVectorIndexOptions) { o.SourceModel = &v })
	return b
}

// DropDatabaseOption is a convenience alias for Builder[DropDatabaseOptions].
type DropDatabaseOption = Builder[DropDatabaseOptions]

// Setters implements Builder[DropDatabaseOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[DropDatabaseOptions].
func (o *DropDatabaseOptions) Setters() []func(*DropDatabaseOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for DropDatabaseOptions.
func (o *DropDatabaseOptions) Validate() error { return nil }

// dropDatabaseOptionsBuilder is a builder for DropDatabaseOptions.
type dropDatabaseOptionsBuilder struct {
	setters []func(*DropDatabaseOptions)
}

// DropDatabase creates a new builder for DropDatabaseOptions.
func DropDatabase() *dropDatabaseOptionsBuilder {
	return &dropDatabaseOptionsBuilder{}
}

// Setters implements Builder[DropDatabaseOptions].
func (b *dropDatabaseOptionsBuilder) Setters() []func(*DropDatabaseOptions) {
	return b.setters
}

// SetBlocking sets the Blocking option.
// Blocking controls whether to wait for the database to be fully terminated.
// Defaults to true.
func (b *dropDatabaseOptionsBuilder) SetBlocking(v bool) *dropDatabaseOptionsBuilder {
	b.setters = append(b.setters, func(o *DropDatabaseOptions) { o.Blocking = &v })
	return b
}

// SetPollInterval sets the PollInterval option.
// PollInterval is how often to check the database status when blocking.
// Defaults to DefaultDatabasePollInterval (10 seconds).
func (b *dropDatabaseOptionsBuilder) SetPollInterval(v time.Duration) *dropDatabaseOptionsBuilder {
	b.setters = append(b.setters, func(o *DropDatabaseOptions) { o.PollInterval = &v })
	return b
}

// DropKeyspaceOption is a convenience alias for Builder[DropKeyspaceOptions].
type DropKeyspaceOption = Builder[DropKeyspaceOptions]

// Setters implements Builder[DropKeyspaceOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[DropKeyspaceOptions].
func (o *DropKeyspaceOptions) Setters() []func(*DropKeyspaceOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for DropKeyspaceOptions.
func (o *DropKeyspaceOptions) Validate() error { return nil }

// dropKeyspaceOptionsBuilder is a builder for DropKeyspaceOptions.
type dropKeyspaceOptionsBuilder struct {
	setters []func(*DropKeyspaceOptions)
}

// DropKeyspace creates a new builder for DropKeyspaceOptions.
func DropKeyspace() *dropKeyspaceOptionsBuilder {
	return &dropKeyspaceOptionsBuilder{}
}

// Setters implements Builder[DropKeyspaceOptions].
func (b *dropKeyspaceOptionsBuilder) Setters() []func(*DropKeyspaceOptions) {
	return b.setters
}

// SetBlocking sets the Blocking option.
// Blocking controls whether to wait for the keyspace to be fully terminated.
// Defaults to true.
func (b *dropKeyspaceOptionsBuilder) SetBlocking(v bool) *dropKeyspaceOptionsBuilder {
	b.setters = append(b.setters, func(o *DropKeyspaceOptions) { o.Blocking = &v })
	return b
}

// SetPollInterval sets the PollInterval option.
// PollInterval is how often to check the keyspace status when blocking.
// Defaults to DefaultKeyspacePollInterval (1 second).
func (b *dropKeyspaceOptionsBuilder) SetPollInterval(v time.Duration) *dropKeyspaceOptionsBuilder {
	b.setters = append(b.setters, func(o *DropKeyspaceOptions) { o.PollInterval = &v })
	return b
}

// FindAvailableRegionsOption is a convenience alias for Builder[FindAvailableRegionsOptions].
type FindAvailableRegionsOption = Builder[FindAvailableRegionsOptions]

// Setters implements Builder[FindAvailableRegionsOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[FindAvailableRegionsOptions].
func (o *FindAvailableRegionsOptions) Setters() []func(*FindAvailableRegionsOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for FindAvailableRegionsOptions.
func (o *FindAvailableRegionsOptions) Validate() error { return nil }

// findAvailableRegionsOptionsBuilder is a builder for FindAvailableRegionsOptions.
type findAvailableRegionsOptionsBuilder struct {
	setters []func(*FindAvailableRegionsOptions)
}

// FindAvailableRegions creates a new builder for FindAvailableRegionsOptions.
func FindAvailableRegions() *findAvailableRegionsOptionsBuilder {
	return &findAvailableRegionsOptionsBuilder{}
}

// Setters implements Builder[FindAvailableRegionsOptions].
func (b *findAvailableRegionsOptionsBuilder) Setters() []func(*FindAvailableRegionsOptions) {
	return b.setters
}

// SetFilterByOrg sets the FilterByOrg option.
// FilterByOrg filters by organization access. Whether to only return regions that
// can be used by the caller's organization.
func (b *findAvailableRegionsOptionsBuilder) SetFilterByOrg(v bool) *findAvailableRegionsOptionsBuilder {
	b.setters = append(b.setters, func(o *FindAvailableRegionsOptions) { o.FilterByOrg = &v })
	return b
}

// IndexingOption is a convenience alias for Builder[IndexingOptions].
type IndexingOption = Builder[IndexingOptions]

// Setters implements Builder[IndexingOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[IndexingOptions].
func (o *IndexingOptions) Setters() []func(*IndexingOptions) {
	return NoopBuilder(o)
}

// indexingOptionsBuilder is a builder for IndexingOptions.
type indexingOptionsBuilder struct {
	setters []func(*IndexingOptions)
}

// Indexing creates a new builder for IndexingOptions.
func Indexing() *indexingOptionsBuilder {
	return &indexingOptionsBuilder{}
}

// Setters implements Builder[IndexingOptions].
func (b *indexingOptionsBuilder) Setters() []func(*IndexingOptions) {
	return b.setters
}

// SetAllow sets the Allow option.
// Allow is a list of field paths to index, or ["*"] to index all fields.
// Mutually exclusive with Deny.
func (b *indexingOptionsBuilder) SetAllow(v ...string) *indexingOptionsBuilder {
	b.setters = append(b.setters, func(o *IndexingOptions) { o.Allow = v })
	return b
}

// SetDeny sets the Deny option.
// Deny is a list of field paths to exclude from indexing, or ["*"] to disable indexing entirely.
// Mutually exclusive with Allow.
func (b *indexingOptionsBuilder) SetDeny(v ...string) *indexingOptionsBuilder {
	b.setters = append(b.setters, func(o *IndexingOptions) { o.Deny = v })
	return b
}

// InsertOneOption is a convenience alias for Builder[InsertOneOptions].
type InsertOneOption = Builder[InsertOneOptions]

// Setters implements Builder[InsertOneOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[InsertOneOptions].
func (o *InsertOneOptions) Setters() []func(*InsertOneOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for InsertOneOptions.
func (o *InsertOneOptions) Validate() error { return nil }

// insertOneOptionsBuilder is a builder for InsertOneOptions.
type insertOneOptionsBuilder struct {
	setters []func(*InsertOneOptions)
}

// InsertOne creates a new builder for InsertOneOptions.
func InsertOne() *insertOneOptionsBuilder {
	return &insertOneOptionsBuilder{}
}

// Setters implements Builder[InsertOneOptions].
func (b *insertOneOptionsBuilder) Setters() []func(*InsertOneOptions) {
	return b.setters
}

// SetOrdered sets the Ordered option.
// Ordered controls whether the insert should be ordered.
func (b *insertOneOptionsBuilder) SetOrdered(v bool) *insertOneOptionsBuilder {
	b.setters = append(b.setters, func(o *InsertOneOptions) { o.Ordered = &v })
	return b
}

// SetTimeout sets the Timeout option.
// Timeout sets the timeout for the insert operation (client-side, not sent to the API).
func (b *insertOneOptionsBuilder) SetTimeout(v time.Duration) *insertOneOptionsBuilder {
	b.setters = append(b.setters, func(o *InsertOneOptions) { o.Timeout = &v })
	return b
}

// LexicalOption is a convenience alias for Builder[LexicalOptions].
type LexicalOption = Builder[LexicalOptions]

// Setters implements Builder[LexicalOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[LexicalOptions].
func (o *LexicalOptions) Setters() []func(*LexicalOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for LexicalOptions.
func (o *LexicalOptions) Validate() error { return nil }

// lexicalOptionsBuilder is a builder for LexicalOptions.
type lexicalOptionsBuilder struct {
	setters []func(*LexicalOptions)
}

// Lexical creates a new builder for LexicalOptions.
func Lexical() *lexicalOptionsBuilder {
	return &lexicalOptionsBuilder{}
}

// Setters implements Builder[LexicalOptions].
func (b *lexicalOptionsBuilder) Setters() []func(*LexicalOptions) {
	return b.setters
}

// ListDatabasesOption is a convenience alias for Builder[ListDatabasesOptions].
type ListDatabasesOption = Builder[ListDatabasesOptions]

// Setters implements Builder[ListDatabasesOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[ListDatabasesOptions].
func (o *ListDatabasesOptions) Setters() []func(*ListDatabasesOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for ListDatabasesOptions.
func (o *ListDatabasesOptions) Validate() error { return nil }

// listDatabasesOptionsBuilder is a builder for ListDatabasesOptions.
type listDatabasesOptionsBuilder struct {
	setters []func(*ListDatabasesOptions)
}

// ListDatabases creates a new builder for ListDatabasesOptions.
func ListDatabases() *listDatabasesOptionsBuilder {
	return &listDatabasesOptionsBuilder{}
}

// Setters implements Builder[ListDatabasesOptions].
func (b *listDatabasesOptionsBuilder) Setters() []func(*ListDatabasesOptions) {
	return b.setters
}

// SetInclude sets the Include option.
// Include filters databases by status. Defaults to [DatabaseStatusNonTerminated].
func (b *listDatabasesOptionsBuilder) SetInclude(v DatabaseStatus) *listDatabasesOptionsBuilder {
	b.setters = append(b.setters, func(o *ListDatabasesOptions) { o.Include = &v })
	return b
}

// SetProvider sets the Provider option.
// Provider filters databases by cloud provider. Defaults to [CloudProviderAll].
func (b *listDatabasesOptionsBuilder) SetProvider(v CloudProviderFilter) *listDatabasesOptionsBuilder {
	b.setters = append(b.setters, func(o *ListDatabasesOptions) { o.Provider = &v })
	return b
}

// SetLimit sets the Limit option.
// Limit is the maximum number of databases to return (1-100). Defaults to 25.
func (b *listDatabasesOptionsBuilder) SetLimit(v int) *listDatabasesOptionsBuilder {
	b.setters = append(b.setters, func(o *ListDatabasesOptions) { o.Limit = &v })
	return b
}

// SetStartingAfter sets the StartingAfter option.
// StartingAfter is a database ID to use with pagination. Pass the DB ID of the
// last item on the previous page to get the next page.
func (b *listDatabasesOptionsBuilder) SetStartingAfter(v string) *listDatabasesOptionsBuilder {
	b.setters = append(b.setters, func(o *ListDatabasesOptions) { o.StartingAfter = &v })
	return b
}

// ListIndexesOption is a convenience alias for Builder[ListIndexesOptions].
type ListIndexesOption = Builder[ListIndexesOptions]

// Setters implements Builder[ListIndexesOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[ListIndexesOptions].
func (o *ListIndexesOptions) Setters() []func(*ListIndexesOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for ListIndexesOptions.
func (o *ListIndexesOptions) Validate() error { return nil }

// listIndexesOptionsBuilder is a builder for ListIndexesOptions.
type listIndexesOptionsBuilder struct {
	setters []func(*ListIndexesOptions)
}

// ListIndexes creates a new builder for ListIndexesOptions.
func ListIndexes() *listIndexesOptionsBuilder {
	return &listIndexesOptionsBuilder{}
}

// Setters implements Builder[ListIndexesOptions].
func (b *listIndexesOptionsBuilder) Setters() []func(*ListIndexesOptions) {
	return b.setters
}

// SetExplain sets the Explain option.
// Explain if true, returns full index metadata including definitions.
// If false (default), only returns index names.
func (b *listIndexesOptionsBuilder) SetExplain(v bool) *listIndexesOptionsBuilder {
	b.setters = append(b.setters, func(o *ListIndexesOptions) { o.Explain = &v })
	return b
}

// RerankOption is a convenience alias for Builder[RerankOptions].
type RerankOption = Builder[RerankOptions]

// Setters implements Builder[RerankOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[RerankOptions].
func (o *RerankOptions) Setters() []func(*RerankOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for RerankOptions.
func (o *RerankOptions) Validate() error { return nil }

// rerankOptionsBuilder is a builder for RerankOptions.
type rerankOptionsBuilder struct {
	setters []func(*RerankOptions)
}

// Rerank creates a new builder for RerankOptions.
func Rerank() *rerankOptionsBuilder {
	return &rerankOptionsBuilder{}
}

// Setters implements Builder[RerankOptions].
func (b *rerankOptionsBuilder) Setters() []func(*RerankOptions) {
	return b.setters
}

// SerdesOption is a convenience alias for Builder[SerdesOptions].
type SerdesOption = Builder[SerdesOptions]

// Setters implements Builder[SerdesOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[SerdesOptions].
func (o *SerdesOptions) Setters() []func(*SerdesOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for SerdesOptions.
func (o *SerdesOptions) Validate() error { return nil }

// serdesOptionsBuilder is a builder for SerdesOptions.
type serdesOptionsBuilder struct {
	setters []func(*SerdesOptions)
}

// Serdes creates a new builder for SerdesOptions.
func Serdes() *serdesOptionsBuilder {
	return &serdesOptionsBuilder{}
}

// Setters implements Builder[SerdesOptions].
func (b *serdesOptionsBuilder) Setters() []func(*SerdesOptions) {
	return b.setters
}

// TableFindOption is a convenience alias for Builder[TableFindOptions].
type TableFindOption = Builder[TableFindOptions]

// Setters implements Builder[TableFindOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[TableFindOptions].
func (o *TableFindOptions) Setters() []func(*TableFindOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for TableFindOptions.
func (o *TableFindOptions) Validate() error { return nil }

// tableFindOptionsBuilder is a builder for TableFindOptions.
type tableFindOptionsBuilder struct {
	setters []func(*TableFindOptions)
}

// TableFind creates a new builder for TableFindOptions.
func TableFind() *tableFindOptionsBuilder {
	return &tableFindOptionsBuilder{}
}

// Setters implements Builder[TableFindOptions].
func (b *tableFindOptionsBuilder) Setters() []func(*TableFindOptions) {
	return b.setters
}

// SetSort sets the Sort option.
// Sort specifies how to sort the results. Can be used for:
//   - Ascending/descending sort on columns (e.g., {"rating": 1, "title": -1})
//   - Vector search with a vector (e.g., {"vector_column": [0.1, 0.2, 0.3]})
//   - Vector search with vectorize (e.g., {"vector_column": "search text"})
func (b *tableFindOptionsBuilder) SetSort(v map[string]any) *tableFindOptionsBuilder {
	b.setters = append(b.setters, func(o *TableFindOptions) { o.Sort = v })
	return b
}

// SetProjection sets the Projection option.
// Projection controls which columns are included or excluded in the returned rows
// Use true to include a column, false to exclude it
func (b *tableFindOptionsBuilder) SetProjection(v map[string]bool) *tableFindOptionsBuilder {
	b.setters = append(b.setters, func(o *TableFindOptions) { o.Projection = v })
	return b
}

// SetLimit sets the Limit option.
// Limit limits the total number of rows returned
func (b *tableFindOptionsBuilder) SetLimit(v int) *tableFindOptionsBuilder {
	b.setters = append(b.setters, func(o *TableFindOptions) { o.Limit = &v })
	return b
}

// SetSkip sets the Skip option.
// Skip specifies the number of rows to bypass before returning rows.
// Only valid with ascending/descending sort, not with vector search.
func (b *tableFindOptionsBuilder) SetSkip(v int) *tableFindOptionsBuilder {
	b.setters = append(b.setters, func(o *TableFindOptions) { o.Skip = &v })
	return b
}

// SetIncludeSimilarity sets the IncludeSimilarity option.
// IncludeSimilarity if true, includes a $similarity property in the response
// for vector searches. Only works with direct vector search, not vectorize.
func (b *tableFindOptionsBuilder) SetIncludeSimilarity(v bool) *tableFindOptionsBuilder {
	b.setters = append(b.setters, func(o *TableFindOptions) { o.IncludeSimilarity = &v })
	return b
}

// SetInitialPageState sets the InitialPageState option.
// InitialPageState is used for pagination to fetch the next page of results
func (b *tableFindOptionsBuilder) SetInitialPageState(v string) *tableFindOptionsBuilder {
	b.setters = append(b.setters, func(o *TableFindOptions) { o.InitialPageState = &v })
	return b
}

// TimeoutOption is a convenience alias for Builder[TimeoutOptions].
type TimeoutOption = Builder[TimeoutOptions]

// Setters implements Builder[TimeoutOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[TimeoutOptions].
func (o *TimeoutOptions) Setters() []func(*TimeoutOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for TimeoutOptions.
func (o *TimeoutOptions) Validate() error { return nil }

// timeoutOptionsBuilder is a builder for TimeoutOptions.
type timeoutOptionsBuilder struct {
	setters []func(*TimeoutOptions)
}

// Timeout creates a new builder for TimeoutOptions.
func Timeout() *timeoutOptionsBuilder {
	return &timeoutOptionsBuilder{}
}

// Setters implements Builder[TimeoutOptions].
func (b *timeoutOptionsBuilder) Setters() []func(*TimeoutOptions) {
	return b.setters
}

// SetRequest sets the Request option.
// Request is the timeout for individual HTTP requests
func (b *timeoutOptionsBuilder) SetRequest(v time.Duration) *timeoutOptionsBuilder {
	b.setters = append(b.setters, func(o *TimeoutOptions) { o.Request = &v })
	return b
}

// SetConnection sets the Connection option.
// Connection is the timeout for establishing connections
func (b *timeoutOptionsBuilder) SetConnection(v time.Duration) *timeoutOptionsBuilder {
	b.setters = append(b.setters, func(o *TimeoutOptions) { o.Connection = &v })
	return b
}

// SetBulkOperation sets the BulkOperation option.
// BulkOperation is the timeout for bulk operations like insertMany
func (b *timeoutOptionsBuilder) SetBulkOperation(v time.Duration) *timeoutOptionsBuilder {
	b.setters = append(b.setters, func(o *TimeoutOptions) { o.BulkOperation = &v })
	return b
}

// VectorOption is a convenience alias for Builder[VectorOptions].
type VectorOption = Builder[VectorOptions]

// Setters implements Builder[VectorOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[VectorOptions].
func (o *VectorOptions) Setters() []func(*VectorOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for VectorOptions.
func (o *VectorOptions) Validate() error { return nil }

// vectorOptionsBuilder is a builder for VectorOptions.
type vectorOptionsBuilder struct {
	setters []func(*VectorOptions)
}

// Vector creates a new builder for VectorOptions.
func Vector() *vectorOptionsBuilder {
	return &vectorOptionsBuilder{}
}

// Setters implements Builder[VectorOptions].
func (b *vectorOptionsBuilder) Setters() []func(*VectorOptions) {
	return b.setters
}

// SetDimension sets the Dimension option.
// Dimension specifies the dimension of vectors stored in this collection.
// Required for vector-enabled collections.
func (b *vectorOptionsBuilder) SetDimension(v int) *vectorOptionsBuilder {
	b.setters = append(b.setters, func(o *VectorOptions) { o.Dimension = &v })
	return b
}

// SetMetric sets the Metric option.
// Metric specifies the similarity metric used for vector search.
// Valid values are "cosine", "euclidean", or "dot_product".
// Default is "cosine".
func (b *vectorOptionsBuilder) SetMetric(v string) *vectorOptionsBuilder {
	b.setters = append(b.setters, func(o *VectorOptions) { o.Metric = &v })
	return b
}

// SetService sets the Service option.
// Service configures automatic vector embedding generation (vectorize).
func (b *vectorOptionsBuilder) SetService(v ...Builder[VectorServiceOptions]) *vectorOptionsBuilder {
	b.setters = append(b.setters, func(o *VectorOptions) {
		o.Service = Merge(v...)
	})
	return b
}

// VectorServiceOption is a convenience alias for Builder[VectorServiceOptions].
type VectorServiceOption = Builder[VectorServiceOptions]

// Setters implements Builder[VectorServiceOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[VectorServiceOptions].
func (o *VectorServiceOptions) Setters() []func(*VectorServiceOptions) {
	return NoopBuilder(o)
}

// vectorServiceOptionsBuilder is a builder for VectorServiceOptions.
type vectorServiceOptionsBuilder struct {
	setters []func(*VectorServiceOptions)
}

// VectorService creates a new builder for VectorServiceOptions.
func VectorService() *vectorServiceOptionsBuilder {
	return &vectorServiceOptionsBuilder{}
}

// Setters implements Builder[VectorServiceOptions].
func (b *vectorServiceOptionsBuilder) Setters() []func(*VectorServiceOptions) {
	return b.setters
}

// SetProvider sets the Provider option.
// Provider is the embedding provider name (e.g., "openai", "huggingface").
func (b *vectorServiceOptionsBuilder) SetProvider(v string) *vectorServiceOptionsBuilder {
	b.setters = append(b.setters, func(o *VectorServiceOptions) { o.Provider = &v })
	return b
}

// SetModelName sets the ModelName option.
// ModelName is the name of the embedding model to use.
func (b *vectorServiceOptionsBuilder) SetModelName(v string) *vectorServiceOptionsBuilder {
	b.setters = append(b.setters, func(o *VectorServiceOptions) { o.ModelName = &v })
	return b
}
