// Copyright DataStax, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-options; DO NOT EDIT.

package options

import (
	"net/http"
	"time"
)

// Setters implements Builder[APIOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[APIOptions].
func (o *APIOptions) Setters() []func(*APIOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for APIOptions.
func (o *APIOptions) Validate() error { return nil }

// APIOptionsBuilder is a builder for APIOptions.
type APIOptionsBuilder struct {
	Opts []func(*APIOptions)
}

// API creates a new APIOptionsBuilder.
func API() *APIOptionsBuilder {
	return &APIOptionsBuilder{}
}

// Setters implements Builder[APIOptions].
func (b *APIOptionsBuilder) Setters() []func(*APIOptions) {
	return b.Opts
}

// SetToken sets the Token option.
// Token is the authentication token for Astra DB
func (b *APIOptionsBuilder) SetToken(v string) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) { o.Token = &v })
	return b
}

// SetKeyspace sets the Keyspace option.
// Keyspace is the keyspace to use for operations
func (b *APIOptionsBuilder) SetKeyspace(v string) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) { o.Keyspace = &v })
	return b
}

// SetAPIVersion sets the APIVersion option.
// APIVersion is the Data API version (e.g., "v1")
func (b *APIOptionsBuilder) SetAPIVersion(v string) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) { o.APIVersion = &v })
	return b
}

// SetHTTPClient sets the HTTPClient option.
// HTTPClient is the HTTP client to use for requests
func (b *APIOptionsBuilder) SetHTTPClient(v http.Client) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) { o.HTTPClient = &v })
	return b
}

// SetHeaders sets the Headers option.
// Headers contains custom headers to include in requests
// (e.g., for embedding API keys like "x-embedding-api-key")
func (b *APIOptionsBuilder) SetHeaders(v map[string]string) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) { o.Headers = v })
	return b
}

// SetTimeout sets the Timeout option.
// Timeout contains timeout configuration
func (b *APIOptionsBuilder) SetTimeout(v ...Builder[TimeoutOptions]) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) {
		o.Timeout = Merge(v...)
	})
	return b
}

// SetSerdes sets the Serdes option.
// Serdes contains serialization/deserialization options
func (b *APIOptionsBuilder) SetSerdes(v ...Builder[SerdesOptions]) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) {
		o.Serdes = Merge(v...)
	})
	return b
}

// SetAstraEnvironment sets the AstraEnvironment option.
// AstraEnvironment is the Astra environment (prod, dev, test).
// Controls the DevOps API URL. Defaults to prod.
func (b *APIOptionsBuilder) SetAstraEnvironment(v AstraEnvironment) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) { o.AstraEnvironment = &v })
	return b
}

// SetDataAPIBackend sets the DataAPIBackend option.
// DataAPIBackend is the database backend (astra, hcd, dse, cassandra, other).
// Controls the Data API path. Defaults to astra.
func (b *APIOptionsBuilder) SetDataAPIBackend(v DataAPIBackend) *APIOptionsBuilder {
	b.Opts = append(b.Opts, func(o *APIOptions) { o.DataAPIBackend = &v })
	return b
}

// CollectionDefaultIdOption is a convenience alias for Builder[CollectionDefaultIdOptions].
type CollectionDefaultIdOption = Builder[CollectionDefaultIdOptions]

// Setters implements Builder[CollectionDefaultIdOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CollectionDefaultIdOptions].
func (o *CollectionDefaultIdOptions) Setters() []func(*CollectionDefaultIdOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CollectionDefaultIdOptions.
func (o *CollectionDefaultIdOptions) Validate() error { return nil }

// CollectionDefaultIdOptionsBuilder is a builder for CollectionDefaultIdOptions.
type CollectionDefaultIdOptionsBuilder struct {
	Opts []func(*CollectionDefaultIdOptions)
}

// CollectionDefaultId creates a new CollectionDefaultIdOptionsBuilder.
func CollectionDefaultId() *CollectionDefaultIdOptionsBuilder {
	return &CollectionDefaultIdOptionsBuilder{}
}

// Setters implements Builder[CollectionDefaultIdOptions].
func (b *CollectionDefaultIdOptionsBuilder) Setters() []func(*CollectionDefaultIdOptions) {
	return b.Opts
}

// SetType sets the Type option.
// Type is the type of the default ID that the API should generate if no ID is provided in the inserted document.
// Valid values: "uuid", "uuidv6", "uuidv7", "objectId".
// If not specified, the default ID will be a string UUID.
func (b *CollectionDefaultIdOptionsBuilder) SetType(v DefaultIdType) *CollectionDefaultIdOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionDefaultIdOptions) { o.Type = &v })
	return b
}

// CollectionFindOption is a convenience alias for Builder[CollectionFindOptions].
type CollectionFindOption = Builder[CollectionFindOptions]

// Setters implements Builder[CollectionFindOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CollectionFindOptions].
func (o *CollectionFindOptions) Setters() []func(*CollectionFindOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CollectionFindOptions.
func (o *CollectionFindOptions) Validate() error { return nil }

// CollectionFindOptionsBuilder is a builder for CollectionFindOptions.
type CollectionFindOptionsBuilder struct {
	Opts []func(*CollectionFindOptions)
}

// CollectionFind creates a new CollectionFindOptionsBuilder.
func CollectionFind() *CollectionFindOptionsBuilder {
	return &CollectionFindOptionsBuilder{}
}

// Setters implements Builder[CollectionFindOptions].
func (b *CollectionFindOptionsBuilder) Setters() []func(*CollectionFindOptions) {
	return b.Opts
}

// SetSort sets the Sort option.
// Sort specifies how to sort the results. Can be used for:
//   - Ascending/descending sort on fields (e.g., {"rating": 1, "title": -1})
//   - Vector search with a vector (e.g., {"$vector": [0.1, 0.2, 0.3]})
//   - Vector search with vectorize (e.g., {"$vectorize": "search text"})
func (b *CollectionFindOptionsBuilder) SetSort(v map[string]any) *CollectionFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionFindOptions) { o.Sort = v })
	return b
}

// SetProjection sets the Projection option.
// Projection controls which fields are included or excluded in the returned documents
// Use true to include a field, false to exclude it
func (b *CollectionFindOptionsBuilder) SetProjection(v map[string]any) *CollectionFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionFindOptions) { o.Projection = v })
	return b
}

// SetLimit sets the Limit option.
// Limit limits the total number of documents returned
func (b *CollectionFindOptionsBuilder) SetLimit(v int) *CollectionFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionFindOptions) { o.Limit = &v })
	return b
}

// SetSkip sets the Skip option.
// Skip specifies the number of documents to bypass before returning results.
// Only valid with ascending/descending sort, not with vector search.
func (b *CollectionFindOptionsBuilder) SetSkip(v int) *CollectionFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionFindOptions) { o.Skip = &v })
	return b
}

// SetIncludeSimilarity sets the IncludeSimilarity option.
// IncludeSimilarity if true, includes a $similarity property in the response
// for vector searches.
func (b *CollectionFindOptionsBuilder) SetIncludeSimilarity(v bool) *CollectionFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionFindOptions) { o.IncludeSimilarity = &v })
	return b
}

// SetIncludeSortVector sets the IncludeSortVector option.
// IncludeSortVector if true, includes the sort vector in the response.
// Useful for vector searches using $vectorize.
func (b *CollectionFindOptionsBuilder) SetIncludeSortVector(v bool) *CollectionFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionFindOptions) { o.IncludeSortVector = &v })
	return b
}

// SetInitialPageState sets the InitialPageState option.
// InitialPageState is used for pagination to fetch the next page of results
func (b *CollectionFindOptionsBuilder) SetInitialPageState(v string) *CollectionFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionFindOptions) { o.InitialPageState = &v })
	return b
}

// CollectionUpdateOneOption is a convenience alias for Builder[CollectionUpdateOneOptions].
type CollectionUpdateOneOption = Builder[CollectionUpdateOneOptions]

// Setters implements Builder[CollectionUpdateOneOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CollectionUpdateOneOptions].
func (o *CollectionUpdateOneOptions) Setters() []func(*CollectionUpdateOneOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CollectionUpdateOneOptions.
func (o *CollectionUpdateOneOptions) Validate() error { return nil }

// CollectionUpdateOneOptionsBuilder is a builder for CollectionUpdateOneOptions.
type CollectionUpdateOneOptionsBuilder struct {
	Opts []func(*CollectionUpdateOneOptions)
}

// CollectionUpdateOne creates a new CollectionUpdateOneOptionsBuilder.
func CollectionUpdateOne() *CollectionUpdateOneOptionsBuilder {
	return &CollectionUpdateOneOptionsBuilder{}
}

// Setters implements Builder[CollectionUpdateOneOptions].
func (b *CollectionUpdateOneOptionsBuilder) Setters() []func(*CollectionUpdateOneOptions) {
	return b.Opts
}

// SetSort sets the Sort option.
// Sort specifies the sort order to apply before selecting the document to update.
// This determines which document is updated when the filter matches multiple documents.
func (b *CollectionUpdateOneOptionsBuilder) SetSort(v map[string]any) *CollectionUpdateOneOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionUpdateOneOptions) { o.Sort = v })
	return b
}

// SetUpsert sets the Upsert option.
// Upsert if true, inserts a new document if no document matches the filter.
func (b *CollectionUpdateOneOptionsBuilder) SetUpsert(v bool) *CollectionUpdateOneOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CollectionUpdateOneOptions) { o.Upsert = &v })
	return b
}

// CreateCollectionOption is a convenience alias for Builder[CreateCollectionOptions].
type CreateCollectionOption = Builder[CreateCollectionOptions]

// Setters implements Builder[CreateCollectionOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateCollectionOptions].
func (o *CreateCollectionOptions) Setters() []func(*CreateCollectionOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateCollectionOptions.
func (o *CreateCollectionOptions) Validate() error { return nil }

// CreateCollectionOptionsBuilder is a builder for CreateCollectionOptions.
type CreateCollectionOptionsBuilder struct {
	Opts []func(*CreateCollectionOptions)
}

// CreateCollection creates a new CreateCollectionOptionsBuilder.
func CreateCollection() *CreateCollectionOptionsBuilder {
	return &CreateCollectionOptionsBuilder{}
}

// Setters implements Builder[CreateCollectionOptions].
func (b *CreateCollectionOptionsBuilder) Setters() []func(*CreateCollectionOptions) {
	return b.Opts
}

// SetDefaultId sets the DefaultId option.
// Settings for generating ids
func (b *CreateCollectionOptionsBuilder) SetDefaultId(v ...Builder[CollectionDefaultIdOptions]) *CreateCollectionOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateCollectionOptions) {
		o.DefaultId = Merge(v...)
	})
	return b
}

// SetVector sets the Vector option.
// Vector specifications for the collection
func (b *CreateCollectionOptionsBuilder) SetVector(v ...Builder[VectorOptions]) *CreateCollectionOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateCollectionOptions) {
		o.Vector = Merge(v...)
	})
	return b
}

// SetIndexing sets the Indexing option.
// Overrides for document indexing
func (b *CreateCollectionOptionsBuilder) SetIndexing(v ...Builder[IndexingOptions]) *CreateCollectionOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateCollectionOptions) {
		o.Indexing = Merge(v...)
	})
	return b
}

// SetLexical sets the Lexical option.
// Lexical analysis options for the collection
func (b *CreateCollectionOptionsBuilder) SetLexical(v ...Builder[LexicalOptions]) *CreateCollectionOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateCollectionOptions) {
		o.Lexical = Merge(v...)
	})
	return b
}

// SetRerank sets the Rerank option.
// Reranking options for the collection
func (b *CreateCollectionOptionsBuilder) SetRerank(v ...Builder[RerankOptions]) *CreateCollectionOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateCollectionOptions) {
		o.Rerank = Merge(v...)
	})
	return b
}

// CreateDatabaseOption is a convenience alias for Builder[CreateDatabaseOptions].
type CreateDatabaseOption = Builder[CreateDatabaseOptions]

// Setters implements Builder[CreateDatabaseOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateDatabaseOptions].
func (o *CreateDatabaseOptions) Setters() []func(*CreateDatabaseOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateDatabaseOptions.
func (o *CreateDatabaseOptions) Validate() error { return nil }

// CreateDatabaseOptionsBuilder is a builder for CreateDatabaseOptions.
type CreateDatabaseOptionsBuilder struct {
	Opts []func(*CreateDatabaseOptions)
}

// CreateDatabase creates a new CreateDatabaseOptionsBuilder.
func CreateDatabase() *CreateDatabaseOptionsBuilder {
	return &CreateDatabaseOptionsBuilder{}
}

// Setters implements Builder[CreateDatabaseOptions].
func (b *CreateDatabaseOptionsBuilder) Setters() []func(*CreateDatabaseOptions) {
	return b.Opts
}

// SetKeyspace sets the Keyspace option.
// Keyspace is the initial keyspace name. Defaults to "default_keyspace" if not specified.
func (b *CreateDatabaseOptionsBuilder) SetKeyspace(v string) *CreateDatabaseOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateDatabaseOptions) { o.Keyspace = &v })
	return b
}

// SetBlocking sets the Blocking option.
// Blocking controls whether to wait for the database to become ACTIVE.
// Defaults to true.
func (b *CreateDatabaseOptionsBuilder) SetBlocking(v bool) *CreateDatabaseOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateDatabaseOptions) { o.Blocking = &v })
	return b
}

// SetPollInterval sets the PollInterval option.
// PollInterval is how often to check the database status when blocking.
// Defaults to DefaultDatabasePollInterval (10 seconds).
func (b *CreateDatabaseOptionsBuilder) SetPollInterval(v time.Duration) *CreateDatabaseOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateDatabaseOptions) { o.PollInterval = &v })
	return b
}

// CreateIndexOption is a convenience alias for Builder[CreateIndexOptions].
type CreateIndexOption = Builder[CreateIndexOptions]

// Setters implements Builder[CreateIndexOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateIndexOptions].
func (o *CreateIndexOptions) Setters() []func(*CreateIndexOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateIndexOptions.
func (o *CreateIndexOptions) Validate() error { return nil }

// CreateIndexOptionsBuilder is a builder for CreateIndexOptions.
type CreateIndexOptionsBuilder struct {
	Opts []func(*CreateIndexOptions)
}

// CreateIndex creates a new CreateIndexOptionsBuilder.
func CreateIndex() *CreateIndexOptionsBuilder {
	return &CreateIndexOptionsBuilder{}
}

// Setters implements Builder[CreateIndexOptions].
func (b *CreateIndexOptionsBuilder) Setters() []func(*CreateIndexOptions) {
	return b.Opts
}

// SetIfNotExists sets the IfNotExists option.
// IfNotExists if true, the command will silently succeed even if an index
// with the given name already exists. This only checks index names, not definitions.
func (b *CreateIndexOptionsBuilder) SetIfNotExists(v bool) *CreateIndexOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateIndexOptions) { o.IfNotExists = &v })
	return b
}

// SetAscii sets the Ascii option.
// Ascii if true, converts non-ASCII characters to US-ASCII before indexing.
// Only applicable to text columns.
func (b *CreateIndexOptionsBuilder) SetAscii(v bool) *CreateIndexOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateIndexOptions) { o.Ascii = &v })
	return b
}

// SetNormalize sets the Normalize option.
// Normalize if true, applies Unicode character normalization before indexing.
// Only applicable to text columns.
func (b *CreateIndexOptionsBuilder) SetNormalize(v bool) *CreateIndexOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateIndexOptions) { o.Normalize = &v })
	return b
}

// SetCaseSensitive sets the CaseSensitive option.
// CaseSensitive if true (default), enforces case-sensitive matching.
// Only applicable to text columns.
func (b *CreateIndexOptionsBuilder) SetCaseSensitive(v bool) *CreateIndexOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateIndexOptions) { o.CaseSensitive = &v })
	return b
}

// CreateKeyspaceOption is a convenience alias for Builder[CreateKeyspaceOptions].
type CreateKeyspaceOption = Builder[CreateKeyspaceOptions]

// Setters implements Builder[CreateKeyspaceOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateKeyspaceOptions].
func (o *CreateKeyspaceOptions) Setters() []func(*CreateKeyspaceOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateKeyspaceOptions.
func (o *CreateKeyspaceOptions) Validate() error { return nil }

// CreateKeyspaceOptionsBuilder is a builder for CreateKeyspaceOptions.
type CreateKeyspaceOptionsBuilder struct {
	Opts []func(*CreateKeyspaceOptions)
}

// CreateKeyspace creates a new CreateKeyspaceOptionsBuilder.
func CreateKeyspace() *CreateKeyspaceOptionsBuilder {
	return &CreateKeyspaceOptionsBuilder{}
}

// Setters implements Builder[CreateKeyspaceOptions].
func (b *CreateKeyspaceOptionsBuilder) Setters() []func(*CreateKeyspaceOptions) {
	return b.Opts
}

// SetBlocking sets the Blocking option.
// Blocking controls whether to wait for the keyspace to become visible.
// Defaults to true. Only used by the Astra (DevOps API) path.
func (b *CreateKeyspaceOptionsBuilder) SetBlocking(v bool) *CreateKeyspaceOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateKeyspaceOptions) { o.Blocking = &v })
	return b
}

// SetPollInterval sets the PollInterval option.
// PollInterval is how often to check whether the keyspace exists when blocking.
// Defaults to DefaultKeyspacePollInterval (1 second). Only used by the Astra (DevOps API) path.
func (b *CreateKeyspaceOptionsBuilder) SetPollInterval(v time.Duration) *CreateKeyspaceOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateKeyspaceOptions) { o.PollInterval = &v })
	return b
}

// SetReplicationFactor sets the ReplicationFactor option.
// ReplicationFactor sets the replication factor for the keyspace.
// Only used by the Data API path (non-Astra environments).
func (b *CreateKeyspaceOptionsBuilder) SetReplicationFactor(v int) *CreateKeyspaceOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateKeyspaceOptions) { o.ReplicationFactor = &v })
	return b
}

// CreateTableOption is a convenience alias for Builder[CreateTableOptions].
type CreateTableOption = Builder[CreateTableOptions]

// Setters implements Builder[CreateTableOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateTableOptions].
func (o *CreateTableOptions) Setters() []func(*CreateTableOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateTableOptions.
func (o *CreateTableOptions) Validate() error { return nil }

// CreateTableOptionsBuilder is a builder for CreateTableOptions.
type CreateTableOptionsBuilder struct {
	Opts []func(*CreateTableOptions)
}

// CreateTable creates a new CreateTableOptionsBuilder.
func CreateTable() *CreateTableOptionsBuilder {
	return &CreateTableOptionsBuilder{}
}

// Setters implements Builder[CreateTableOptions].
func (b *CreateTableOptionsBuilder) Setters() []func(*CreateTableOptions) {
	return b.Opts
}

// SetIfNotExists sets the IfNotExists option.
// IfNotExists if true, the command will silently succeed even if a table
// with the given name already exists. This only checks table names, not schemas.
func (b *CreateTableOptionsBuilder) SetIfNotExists(v bool) *CreateTableOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateTableOptions) { o.IfNotExists = &v })
	return b
}

// SetKeyspace sets the Keyspace option.
// Keyspace specifies the keyspace in which to create the table.
// If not provided, defaults to the working keyspace for the database.
func (b *CreateTableOptionsBuilder) SetKeyspace(v string) *CreateTableOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateTableOptions) { o.Keyspace = &v })
	return b
}

// CreateVectorIndexOption is a convenience alias for Builder[CreateVectorIndexOptions].
type CreateVectorIndexOption = Builder[CreateVectorIndexOptions]

// Setters implements Builder[CreateVectorIndexOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[CreateVectorIndexOptions].
func (o *CreateVectorIndexOptions) Setters() []func(*CreateVectorIndexOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for CreateVectorIndexOptions.
func (o *CreateVectorIndexOptions) Validate() error { return nil }

// CreateVectorIndexOptionsBuilder is a builder for CreateVectorIndexOptions.
type CreateVectorIndexOptionsBuilder struct {
	Opts []func(*CreateVectorIndexOptions)
}

// CreateVectorIndex creates a new CreateVectorIndexOptionsBuilder.
func CreateVectorIndex() *CreateVectorIndexOptionsBuilder {
	return &CreateVectorIndexOptionsBuilder{}
}

// Setters implements Builder[CreateVectorIndexOptions].
func (b *CreateVectorIndexOptionsBuilder) Setters() []func(*CreateVectorIndexOptions) {
	return b.Opts
}

// SetIfNotExists sets the IfNotExists option.
// IfNotExists if true, the command will silently succeed even if an index
// with the given name already exists. This only checks index names, not definitions.
func (b *CreateVectorIndexOptionsBuilder) SetIfNotExists(v bool) *CreateVectorIndexOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateVectorIndexOptions) { o.IfNotExists = &v })
	return b
}

// SetMetric sets the Metric option.
// Metric is the similarity measurement for vector search.
// Valid values: "cosine" (default), "dot_product", "euclidean"
func (b *CreateVectorIndexOptionsBuilder) SetMetric(v VectorMetric) *CreateVectorIndexOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateVectorIndexOptions) { o.Metric = &v })
	return b
}

// SetSourceModel sets the SourceModel option.
// SourceModel is the embedding generation model, enabling optimizations.
// Valid values: "ada002", "bert", "cohere-v3", "gecko", "nv-qa-4",
// "openai-v3-large", "openai-v3-small", "other" (default)
//
// NOTE: following the other libraries' patterns, we are using a enum-like option for Metric, but
// this is a string. For reference:
// https://docs.datastax.com/en/astra-db-serverless/api-reference/table-index-methods/create-vector-index.html#parameters
func (b *CreateVectorIndexOptionsBuilder) SetSourceModel(v string) *CreateVectorIndexOptionsBuilder {
	b.Opts = append(b.Opts, func(o *CreateVectorIndexOptions) { o.SourceModel = &v })
	return b
}

// DropDatabaseOption is a convenience alias for Builder[DropDatabaseOptions].
type DropDatabaseOption = Builder[DropDatabaseOptions]

// Setters implements Builder[DropDatabaseOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[DropDatabaseOptions].
func (o *DropDatabaseOptions) Setters() []func(*DropDatabaseOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for DropDatabaseOptions.
func (o *DropDatabaseOptions) Validate() error { return nil }

// DropDatabaseOptionsBuilder is a builder for DropDatabaseOptions.
type DropDatabaseOptionsBuilder struct {
	Opts []func(*DropDatabaseOptions)
}

// DropDatabase creates a new DropDatabaseOptionsBuilder.
func DropDatabase() *DropDatabaseOptionsBuilder {
	return &DropDatabaseOptionsBuilder{}
}

// Setters implements Builder[DropDatabaseOptions].
func (b *DropDatabaseOptionsBuilder) Setters() []func(*DropDatabaseOptions) {
	return b.Opts
}

// SetBlocking sets the Blocking option.
// Blocking controls whether to wait for the database to be fully terminated.
// Defaults to true.
func (b *DropDatabaseOptionsBuilder) SetBlocking(v bool) *DropDatabaseOptionsBuilder {
	b.Opts = append(b.Opts, func(o *DropDatabaseOptions) { o.Blocking = &v })
	return b
}

// SetPollInterval sets the PollInterval option.
// PollInterval is how often to check the database status when blocking.
// Defaults to DefaultDatabasePollInterval (10 seconds).
func (b *DropDatabaseOptionsBuilder) SetPollInterval(v time.Duration) *DropDatabaseOptionsBuilder {
	b.Opts = append(b.Opts, func(o *DropDatabaseOptions) { o.PollInterval = &v })
	return b
}

// DropKeyspaceOption is a convenience alias for Builder[DropKeyspaceOptions].
type DropKeyspaceOption = Builder[DropKeyspaceOptions]

// Setters implements Builder[DropKeyspaceOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[DropKeyspaceOptions].
func (o *DropKeyspaceOptions) Setters() []func(*DropKeyspaceOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for DropKeyspaceOptions.
func (o *DropKeyspaceOptions) Validate() error { return nil }

// DropKeyspaceOptionsBuilder is a builder for DropKeyspaceOptions.
type DropKeyspaceOptionsBuilder struct {
	Opts []func(*DropKeyspaceOptions)
}

// DropKeyspace creates a new DropKeyspaceOptionsBuilder.
func DropKeyspace() *DropKeyspaceOptionsBuilder {
	return &DropKeyspaceOptionsBuilder{}
}

// Setters implements Builder[DropKeyspaceOptions].
func (b *DropKeyspaceOptionsBuilder) Setters() []func(*DropKeyspaceOptions) {
	return b.Opts
}

// SetBlocking sets the Blocking option.
// Blocking controls whether to wait for the keyspace to be fully terminated.
// Defaults to true.
func (b *DropKeyspaceOptionsBuilder) SetBlocking(v bool) *DropKeyspaceOptionsBuilder {
	b.Opts = append(b.Opts, func(o *DropKeyspaceOptions) { o.Blocking = &v })
	return b
}

// SetPollInterval sets the PollInterval option.
// PollInterval is how often to check the keyspace status when blocking.
// Defaults to DefaultKeyspacePollInterval (1 second).
func (b *DropKeyspaceOptionsBuilder) SetPollInterval(v time.Duration) *DropKeyspaceOptionsBuilder {
	b.Opts = append(b.Opts, func(o *DropKeyspaceOptions) { o.PollInterval = &v })
	return b
}

// FindAvailableRegionsOption is a convenience alias for Builder[FindAvailableRegionsOptions].
type FindAvailableRegionsOption = Builder[FindAvailableRegionsOptions]

// Setters implements Builder[FindAvailableRegionsOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[FindAvailableRegionsOptions].
func (o *FindAvailableRegionsOptions) Setters() []func(*FindAvailableRegionsOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for FindAvailableRegionsOptions.
func (o *FindAvailableRegionsOptions) Validate() error { return nil }

// FindAvailableRegionsOptionsBuilder is a builder for FindAvailableRegionsOptions.
type FindAvailableRegionsOptionsBuilder struct {
	Opts []func(*FindAvailableRegionsOptions)
}

// FindAvailableRegions creates a new FindAvailableRegionsOptionsBuilder.
func FindAvailableRegions() *FindAvailableRegionsOptionsBuilder {
	return &FindAvailableRegionsOptionsBuilder{}
}

// Setters implements Builder[FindAvailableRegionsOptions].
func (b *FindAvailableRegionsOptionsBuilder) Setters() []func(*FindAvailableRegionsOptions) {
	return b.Opts
}

// SetFilterByOrg sets the FilterByOrg option.
// FilterByOrg filters by organization access. Whether to only return regions that
// can be used by the caller's organization.
func (b *FindAvailableRegionsOptionsBuilder) SetFilterByOrg(v bool) *FindAvailableRegionsOptionsBuilder {
	b.Opts = append(b.Opts, func(o *FindAvailableRegionsOptions) { o.FilterByOrg = &v })
	return b
}

// IndexingOption is a convenience alias for Builder[IndexingOptions].
type IndexingOption = Builder[IndexingOptions]

// Setters implements Builder[IndexingOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[IndexingOptions].
func (o *IndexingOptions) Setters() []func(*IndexingOptions) {
	return NoopBuilder(o)
}

// IndexingOptionsBuilder is a builder for IndexingOptions.
type IndexingOptionsBuilder struct {
	Opts []func(*IndexingOptions)
}

// Indexing creates a new IndexingOptionsBuilder.
func Indexing() *IndexingOptionsBuilder {
	return &IndexingOptionsBuilder{}
}

// Setters implements Builder[IndexingOptions].
func (b *IndexingOptionsBuilder) Setters() []func(*IndexingOptions) {
	return b.Opts
}

// SetAllow sets the Allow option.
// Allow is a list of field paths to index, or ["*"] to index all fields.
// Mutually exclusive with Deny.
func (b *IndexingOptionsBuilder) SetAllow(v ...string) *IndexingOptionsBuilder {
	b.Opts = append(b.Opts, func(o *IndexingOptions) { o.Allow = v })
	return b
}

// SetDeny sets the Deny option.
// Deny is a list of field paths to exclude from indexing, or ["*"] to disable indexing entirely.
// Mutually exclusive with Allow.
func (b *IndexingOptionsBuilder) SetDeny(v ...string) *IndexingOptionsBuilder {
	b.Opts = append(b.Opts, func(o *IndexingOptions) { o.Deny = v })
	return b
}

// InsertOneOption is a convenience alias for Builder[InsertOneOptions].
type InsertOneOption = Builder[InsertOneOptions]

// Setters implements Builder[InsertOneOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[InsertOneOptions].
func (o *InsertOneOptions) Setters() []func(*InsertOneOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for InsertOneOptions.
func (o *InsertOneOptions) Validate() error { return nil }

// InsertOneOptionsBuilder is a builder for InsertOneOptions.
type InsertOneOptionsBuilder struct {
	Opts []func(*InsertOneOptions)
}

// InsertOne creates a new InsertOneOptionsBuilder.
func InsertOne() *InsertOneOptionsBuilder {
	return &InsertOneOptionsBuilder{}
}

// Setters implements Builder[InsertOneOptions].
func (b *InsertOneOptionsBuilder) Setters() []func(*InsertOneOptions) {
	return b.Opts
}

// SetOrdered sets the Ordered option.
// Ordered controls whether the insert should be ordered.
func (b *InsertOneOptionsBuilder) SetOrdered(v bool) *InsertOneOptionsBuilder {
	b.Opts = append(b.Opts, func(o *InsertOneOptions) { o.Ordered = &v })
	return b
}

// SetTimeout sets the Timeout option.
// Timeout sets the timeout for the insert operation (client-side, not sent to the API).
func (b *InsertOneOptionsBuilder) SetTimeout(v time.Duration) *InsertOneOptionsBuilder {
	b.Opts = append(b.Opts, func(o *InsertOneOptions) { o.Timeout = &v })
	return b
}

// LexicalOption is a convenience alias for Builder[LexicalOptions].
type LexicalOption = Builder[LexicalOptions]

// Setters implements Builder[LexicalOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[LexicalOptions].
func (o *LexicalOptions) Setters() []func(*LexicalOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for LexicalOptions.
func (o *LexicalOptions) Validate() error { return nil }

// LexicalOptionsBuilder is a builder for LexicalOptions.
type LexicalOptionsBuilder struct {
	Opts []func(*LexicalOptions)
}

// Lexical creates a new LexicalOptionsBuilder.
func Lexical() *LexicalOptionsBuilder {
	return &LexicalOptionsBuilder{}
}

// Setters implements Builder[LexicalOptions].
func (b *LexicalOptionsBuilder) Setters() []func(*LexicalOptions) {
	return b.Opts
}

// ListDatabasesOption is a convenience alias for Builder[ListDatabasesOptions].
type ListDatabasesOption = Builder[ListDatabasesOptions]

// Setters implements Builder[ListDatabasesOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[ListDatabasesOptions].
func (o *ListDatabasesOptions) Setters() []func(*ListDatabasesOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for ListDatabasesOptions.
func (o *ListDatabasesOptions) Validate() error { return nil }

// ListDatabasesOptionsBuilder is a builder for ListDatabasesOptions.
type ListDatabasesOptionsBuilder struct {
	Opts []func(*ListDatabasesOptions)
}

// ListDatabases creates a new ListDatabasesOptionsBuilder.
func ListDatabases() *ListDatabasesOptionsBuilder {
	return &ListDatabasesOptionsBuilder{}
}

// Setters implements Builder[ListDatabasesOptions].
func (b *ListDatabasesOptionsBuilder) Setters() []func(*ListDatabasesOptions) {
	return b.Opts
}

// SetInclude sets the Include option.
// Include filters databases by status. Defaults to [DatabaseStatusNonTerminated].
func (b *ListDatabasesOptionsBuilder) SetInclude(v DatabaseStatus) *ListDatabasesOptionsBuilder {
	b.Opts = append(b.Opts, func(o *ListDatabasesOptions) { o.Include = &v })
	return b
}

// SetProvider sets the Provider option.
// Provider filters databases by cloud provider. Defaults to [CloudProviderAll].
func (b *ListDatabasesOptionsBuilder) SetProvider(v CloudProviderFilter) *ListDatabasesOptionsBuilder {
	b.Opts = append(b.Opts, func(o *ListDatabasesOptions) { o.Provider = &v })
	return b
}

// SetLimit sets the Limit option.
// Limit is the maximum number of databases to return (1-100). Defaults to 25.
func (b *ListDatabasesOptionsBuilder) SetLimit(v int) *ListDatabasesOptionsBuilder {
	b.Opts = append(b.Opts, func(o *ListDatabasesOptions) { o.Limit = &v })
	return b
}

// SetStartingAfter sets the StartingAfter option.
// StartingAfter is a database ID to use with pagination. Pass the DB ID of the
// last item on the previous page to get the next page.
func (b *ListDatabasesOptionsBuilder) SetStartingAfter(v string) *ListDatabasesOptionsBuilder {
	b.Opts = append(b.Opts, func(o *ListDatabasesOptions) { o.StartingAfter = &v })
	return b
}

// ListIndexesOption is a convenience alias for Builder[ListIndexesOptions].
type ListIndexesOption = Builder[ListIndexesOptions]

// Setters implements Builder[ListIndexesOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[ListIndexesOptions].
func (o *ListIndexesOptions) Setters() []func(*ListIndexesOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for ListIndexesOptions.
func (o *ListIndexesOptions) Validate() error { return nil }

// ListIndexesOptionsBuilder is a builder for ListIndexesOptions.
type ListIndexesOptionsBuilder struct {
	Opts []func(*ListIndexesOptions)
}

// ListIndexes creates a new ListIndexesOptionsBuilder.
func ListIndexes() *ListIndexesOptionsBuilder {
	return &ListIndexesOptionsBuilder{}
}

// Setters implements Builder[ListIndexesOptions].
func (b *ListIndexesOptionsBuilder) Setters() []func(*ListIndexesOptions) {
	return b.Opts
}

// SetExplain sets the Explain option.
// Explain if true, returns full index metadata including definitions.
// If false (default), only returns index names.
func (b *ListIndexesOptionsBuilder) SetExplain(v bool) *ListIndexesOptionsBuilder {
	b.Opts = append(b.Opts, func(o *ListIndexesOptions) { o.Explain = &v })
	return b
}

// RerankOption is a convenience alias for Builder[RerankOptions].
type RerankOption = Builder[RerankOptions]

// Setters implements Builder[RerankOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[RerankOptions].
func (o *RerankOptions) Setters() []func(*RerankOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for RerankOptions.
func (o *RerankOptions) Validate() error { return nil }

// RerankOptionsBuilder is a builder for RerankOptions.
type RerankOptionsBuilder struct {
	Opts []func(*RerankOptions)
}

// Rerank creates a new RerankOptionsBuilder.
func Rerank() *RerankOptionsBuilder {
	return &RerankOptionsBuilder{}
}

// Setters implements Builder[RerankOptions].
func (b *RerankOptionsBuilder) Setters() []func(*RerankOptions) {
	return b.Opts
}

// SerdesOption is a convenience alias for Builder[SerdesOptions].
type SerdesOption = Builder[SerdesOptions]

// Setters implements Builder[SerdesOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[SerdesOptions].
func (o *SerdesOptions) Setters() []func(*SerdesOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for SerdesOptions.
func (o *SerdesOptions) Validate() error { return nil }

// SerdesOptionsBuilder is a builder for SerdesOptions.
type SerdesOptionsBuilder struct {
	Opts []func(*SerdesOptions)
}

// Serdes creates a new SerdesOptionsBuilder.
func Serdes() *SerdesOptionsBuilder {
	return &SerdesOptionsBuilder{}
}

// Setters implements Builder[SerdesOptions].
func (b *SerdesOptionsBuilder) Setters() []func(*SerdesOptions) {
	return b.Opts
}

// TableFindOption is a convenience alias for Builder[TableFindOptions].
type TableFindOption = Builder[TableFindOptions]

// Setters implements Builder[TableFindOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[TableFindOptions].
func (o *TableFindOptions) Setters() []func(*TableFindOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for TableFindOptions.
func (o *TableFindOptions) Validate() error { return nil }

// TableFindOptionsBuilder is a builder for TableFindOptions.
type TableFindOptionsBuilder struct {
	Opts []func(*TableFindOptions)
}

// TableFind creates a new TableFindOptionsBuilder.
func TableFind() *TableFindOptionsBuilder {
	return &TableFindOptionsBuilder{}
}

// Setters implements Builder[TableFindOptions].
func (b *TableFindOptionsBuilder) Setters() []func(*TableFindOptions) {
	return b.Opts
}

// SetSort sets the Sort option.
// Sort specifies how to sort the results. Can be used for:
//   - Ascending/descending sort on columns (e.g., {"rating": 1, "title": -1})
//   - Vector search with a vector (e.g., {"vector_column": [0.1, 0.2, 0.3]})
//   - Vector search with vectorize (e.g., {"vector_column": "search text"})
func (b *TableFindOptionsBuilder) SetSort(v map[string]any) *TableFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TableFindOptions) { o.Sort = v })
	return b
}

// SetProjection sets the Projection option.
// Projection controls which columns are included or excluded in the returned rows
// Use true to include a column, false to exclude it
func (b *TableFindOptionsBuilder) SetProjection(v map[string]bool) *TableFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TableFindOptions) { o.Projection = v })
	return b
}

// SetLimit sets the Limit option.
// Limit limits the total number of rows returned
func (b *TableFindOptionsBuilder) SetLimit(v int) *TableFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TableFindOptions) { o.Limit = &v })
	return b
}

// SetSkip sets the Skip option.
// Skip specifies the number of rows to bypass before returning rows.
// Only valid with ascending/descending sort, not with vector search.
func (b *TableFindOptionsBuilder) SetSkip(v int) *TableFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TableFindOptions) { o.Skip = &v })
	return b
}

// SetIncludeSimilarity sets the IncludeSimilarity option.
// IncludeSimilarity if true, includes a $similarity property in the response
// for vector searches. Only works with direct vector search, not vectorize.
func (b *TableFindOptionsBuilder) SetIncludeSimilarity(v bool) *TableFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TableFindOptions) { o.IncludeSimilarity = &v })
	return b
}

// SetInitialPageState sets the InitialPageState option.
// InitialPageState is used for pagination to fetch the next page of results
func (b *TableFindOptionsBuilder) SetInitialPageState(v string) *TableFindOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TableFindOptions) { o.InitialPageState = &v })
	return b
}

// TimeoutOption is a convenience alias for Builder[TimeoutOptions].
type TimeoutOption = Builder[TimeoutOptions]

// Setters implements Builder[TimeoutOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[TimeoutOptions].
func (o *TimeoutOptions) Setters() []func(*TimeoutOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for TimeoutOptions.
func (o *TimeoutOptions) Validate() error { return nil }

// TimeoutOptionsBuilder is a builder for TimeoutOptions.
type TimeoutOptionsBuilder struct {
	Opts []func(*TimeoutOptions)
}

// Timeout creates a new TimeoutOptionsBuilder.
func Timeout() *TimeoutOptionsBuilder {
	return &TimeoutOptionsBuilder{}
}

// Setters implements Builder[TimeoutOptions].
func (b *TimeoutOptionsBuilder) Setters() []func(*TimeoutOptions) {
	return b.Opts
}

// SetRequest sets the Request option.
// Request is the timeout for individual HTTP requests
func (b *TimeoutOptionsBuilder) SetRequest(v time.Duration) *TimeoutOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TimeoutOptions) { o.Request = &v })
	return b
}

// SetConnection sets the Connection option.
// Connection is the timeout for establishing connections
func (b *TimeoutOptionsBuilder) SetConnection(v time.Duration) *TimeoutOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TimeoutOptions) { o.Connection = &v })
	return b
}

// SetBulkOperation sets the BulkOperation option.
// BulkOperation is the timeout for bulk operations like insertMany
func (b *TimeoutOptionsBuilder) SetBulkOperation(v time.Duration) *TimeoutOptionsBuilder {
	b.Opts = append(b.Opts, func(o *TimeoutOptions) { o.BulkOperation = &v })
	return b
}

// VectorOption is a convenience alias for Builder[VectorOptions].
type VectorOption = Builder[VectorOptions]

// Setters implements Builder[VectorOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[VectorOptions].
func (o *VectorOptions) Setters() []func(*VectorOptions) {
	return NoopBuilder(o)
}

// Validate implements Validator for VectorOptions.
func (o *VectorOptions) Validate() error { return nil }

// VectorOptionsBuilder is a builder for VectorOptions.
type VectorOptionsBuilder struct {
	Opts []func(*VectorOptions)
}

// Vector creates a new VectorOptionsBuilder.
func Vector() *VectorOptionsBuilder {
	return &VectorOptionsBuilder{}
}

// Setters implements Builder[VectorOptions].
func (b *VectorOptionsBuilder) Setters() []func(*VectorOptions) {
	return b.Opts
}

// SetDimension sets the Dimension option.
// Dimension specifies the dimension of vectors stored in this collection.
// Required for vector-enabled collections.
func (b *VectorOptionsBuilder) SetDimension(v int) *VectorOptionsBuilder {
	b.Opts = append(b.Opts, func(o *VectorOptions) { o.Dimension = &v })
	return b
}

// SetMetric sets the Metric option.
// Metric specifies the similarity metric used for vector search.
// Valid values are "cosine", "euclidean", or "dot_product".
// Default is "cosine".
func (b *VectorOptionsBuilder) SetMetric(v string) *VectorOptionsBuilder {
	b.Opts = append(b.Opts, func(o *VectorOptions) { o.Metric = &v })
	return b
}

// SetService sets the Service option.
// Service configures automatic vector embedding generation (vectorize).
func (b *VectorOptionsBuilder) SetService(v ...Builder[VectorServiceOptions]) *VectorOptionsBuilder {
	b.Opts = append(b.Opts, func(o *VectorOptions) {
		o.Service = Merge(v...)
	})
	return b
}

// VectorServiceOption is a convenience alias for Builder[VectorServiceOptions].
type VectorServiceOption = Builder[VectorServiceOptions]

// Setters implements Builder[VectorServiceOptions] allowing the raw struct to be
// passed directly to methods that accept ...Builder[VectorServiceOptions].
func (o *VectorServiceOptions) Setters() []func(*VectorServiceOptions) {
	return NoopBuilder(o)
}

// VectorServiceOptionsBuilder is a builder for VectorServiceOptions.
type VectorServiceOptionsBuilder struct {
	Opts []func(*VectorServiceOptions)
}

// VectorService creates a new VectorServiceOptionsBuilder.
func VectorService() *VectorServiceOptionsBuilder {
	return &VectorServiceOptionsBuilder{}
}

// Setters implements Builder[VectorServiceOptions].
func (b *VectorServiceOptionsBuilder) Setters() []func(*VectorServiceOptions) {
	return b.Opts
}

// SetProvider sets the Provider option.
// Provider is the embedding provider name (e.g., "openai", "huggingface").
func (b *VectorServiceOptionsBuilder) SetProvider(v string) *VectorServiceOptionsBuilder {
	b.Opts = append(b.Opts, func(o *VectorServiceOptions) { o.Provider = &v })
	return b
}

// SetModelName sets the ModelName option.
// ModelName is the name of the embedding model to use.
func (b *VectorServiceOptionsBuilder) SetModelName(v string) *VectorServiceOptionsBuilder {
	b.Opts = append(b.Opts, func(o *VectorServiceOptions) { o.ModelName = &v })
	return b
}
