// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-options; DO NOT EDIT.

package options

// Children implements ChildValidator for APIOptions.
// Returns all non-nil Validator fields.
func (o *APIOptions) Children() []Validator {
	var children []Validator
	if o.Timeout != nil {
		children = append(children, o.Timeout)
	}
	if o.Serdes != nil {
		children = append(children, o.Serdes)
	}
	return children
}

// Children implements ChildValidator for CollectionDeleteManyOptions.
// Returns all non-nil Validator fields.
func (o *CollectionDeleteManyOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionDeleteOneOptions.
// Returns all non-nil Validator fields.
func (o *CollectionDeleteOneOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOneAndDeleteOptions.
// Returns all non-nil Validator fields.
func (o *CollectionFindOneAndDeleteOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOneAndReplaceOptions.
// Returns all non-nil Validator fields.
func (o *CollectionFindOneAndReplaceOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOneAndUpdateOptions.
// Returns all non-nil Validator fields.
func (o *CollectionFindOneAndUpdateOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOneOptions.
// Returns all non-nil Validator fields.
func (o *CollectionFindOneOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionFindOptions.
// Returns all non-nil Validator fields.
func (o *CollectionFindOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionInsertManyOptions.
// Returns all non-nil Validator fields.
func (o *CollectionInsertManyOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionReplaceOneOptions.
// Returns all non-nil Validator fields.
func (o *CollectionReplaceOneOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionUpdateManyOptions.
// Returns all non-nil Validator fields.
func (o *CollectionUpdateManyOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CollectionUpdateOneOptions.
// Returns all non-nil Validator fields.
func (o *CollectionUpdateOneOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for CreateCollectionOptions.
// Returns all non-nil Validator fields.
func (o *CreateCollectionOptions) Children() []Validator {
	var children []Validator
	if o.DefaultId != nil {
		children = append(children, o.DefaultId)
	}
	if o.Vector != nil {
		children = append(children, o.Vector)
	}
	if o.Indexing != nil {
		children = append(children, o.Indexing)
	}
	if o.Lexical != nil {
		children = append(children, o.Lexical)
	}
	if o.Rerank != nil {
		children = append(children, o.Rerank)
	}
	return children
}

// Children implements ChildValidator for TableFindOptions.
// Returns all non-nil Validator fields.
func (o *TableFindOptions) Children() []Validator {
	var children []Validator
	if o.APIOptions != nil {
		children = append(children, o.APIOptions)
	}
	return children
}

// Children implements ChildValidator for VectorOptions.
// Returns all non-nil Validator fields.
func (o *VectorOptions) Children() []Validator {
	var children []Validator
	if o.Service != nil {
		children = append(children, o.Service)
	}
	return children
}
