// Copyright DataStax, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// gen-update generates top-level constructor functions for the update package.
// For each exported method on *Updater (excluding MarshalJSON and unexported
// methods), it emits a package-level func that delegates to New().<Method>(...).
//
// Usage (via go:generate in update/update.go):
//
//	//go:generate go run -modfile=../tools/gen-update/go.mod ../tools/gen-update -pkg .
//
// Output file:
//
//	constructors_gen.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/imports"
)

const boilerplate = `// Copyright DataStax, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-update; DO NOT EDIT.

`

// skipMethods lists methods on *Updater that should NOT get top-level constructors.
var skipMethods = map[string]bool{
	"MarshalJSON": true,
}

// methodInfo holds the extracted details for one *Updater method.
type methodInfo struct {
	Name    string // e.g. "Set", "Inc", etc.
	Doc     string // doc comment block (with leading //)
	Params  string // e.g. "field string, value any"
	Args    string // e.g. "field, value"
	Returns string // e.g. "*Updater"
}

func main() {
	pkgDir := flag.String("pkg", ".", "package directory to inspect")
	flag.Parse()

	methods := extractMethods(*pkgDir)
	if len(methods) == 0 {
		log.Fatal("no exported *Updater methods found")
	}

	// Generate our src
	src := generate(methods)
	// Then gofmt / add imports as needed.
	formatted, err := imports.Process("constructors_gen.go", src, nil)
	if err != nil {
		log.Fatalf("goimports failed: %v\n\n%s", err, src)
	}

	outPath := filepath.Join(*pkgDir, "constructors_gen.go")
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		log.Fatalf("write: %v", err)
	}
	fmt.Printf("wrote %s\n", outPath)
}

func extractMethods(dir string) []methodInfo {
	fset := token.NewFileSet()
	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatalf("readdir: %v", err)
	}

	var files []*ast.File
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".go") ||
			strings.HasSuffix(name, "_test.go") || strings.Contains(name, "_gen") {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, name), nil, parser.ParseComments)
		if err != nil {
			log.Fatalf("parse %s: %v", name, err)
		}
		files = append(files, f)
	}

	var methods []methodInfo
	for _, file := range files {
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv == nil || len(fn.Recv.List) == 0 {
				continue
			}
			// Skip if unexported or in our skip list.
			if !fn.Name.IsExported() || skipMethods[fn.Name.Name] {
				continue
			}
			// Must be a *Updater receiver.
			star, ok := fn.Recv.List[0].Type.(*ast.StarExpr)
			if !ok {
				continue
			}
			ident, ok := star.X.(*ast.Ident)
			if !ok || ident.Name != "Updater" {
				continue
			}

			mi := methodInfo{Name: fn.Name.Name}

			// Extract doc comment.
			if fn.Doc != nil {
				mi.Doc = strings.TrimRight(fn.Doc.Text(), "\n")
			}

			// Extract params and args.
			mi.Params, mi.Args = renderParamsAndArgs(fset, fn.Type.Params)

			// Extract return type.
			mi.Returns = renderResults(fset, fn.Type.Results)

			methods = append(methods, mi)
		}
	}
	return methods
}

// renderParamsAndArgs renders the parameter list as a Go source string and
// a corresponding argument-forwarding string.
func renderParamsAndArgs(fset *token.FileSet, fields *ast.FieldList) (params, args string) {
	if fields == nil || len(fields.List) == 0 {
		return "", ""
	}

	var paramParts, argParts []string
	for _, field := range fields.List {
		typeStr := nodeString(fset, field.Type)
		isVariadic := false
		if _, ok := field.Type.(*ast.Ellipsis); ok {
			isVariadic = true
		}

		for _, name := range field.Names {
			if isVariadic {
				paramParts = append(paramParts, name.Name+" "+typeStr)
				argParts = append(argParts, name.Name+"...")
			} else {
				paramParts = append(paramParts, name.Name+" "+typeStr)
				argParts = append(argParts, name.Name)
			}
		}
	}
	return strings.Join(paramParts, ", "), strings.Join(argParts, ", ")
}

func renderResults(fset *token.FileSet, fields *ast.FieldList) string {
	if fields == nil || len(fields.List) == 0 {
		return ""
	}
	if len(fields.List) == 1 && len(fields.List[0].Names) == 0 {
		return nodeString(fset, fields.List[0].Type)
	}
	// Multiple returns — shouldn't happen for Updater methods but handle it.
	var parts []string
	for _, f := range fields.List {
		ts := nodeString(fset, f.Type)
		if len(f.Names) == 0 {
			parts = append(parts, ts)
		} else {
			for _, n := range f.Names {
				parts = append(parts, n.Name+" "+ts)
			}
		}
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func nodeString(fset *token.FileSet, node ast.Node) string {
	var buf bytes.Buffer
	printer.Fprint(&buf, fset, node)
	return buf.String()
}

func generate(methods []methodInfo) []byte {
	var buf bytes.Buffer
	buf.WriteString(boilerplate)
	buf.WriteString("package update\n")

	for _, m := range methods {
		buf.WriteString("\n")
		// Write doc comment.
		if m.Doc != "" {
			for _, line := range strings.Split(m.Doc, "\n") {
				fmt.Fprintf(&buf, "// %s\n", line)
			}
		}
		// Write function.
		fmt.Fprintf(&buf, "func %s(%s) %s { return New().%s(%s) }\n",
			m.Name, m.Params, m.Returns, m.Name, m.Args)
	}

	return buf.Bytes()
}
