// Copyright DataStax, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-update; DO NOT EDIT.

package update

// The $set operator sets the value of the specified field to the specified value.
//
// Example usage:
//
//	update.Set("number_of_pages", 423).Set("rating", 4.5)
func Set(field string, value any) *Updater { return New().Set(field, value) }

// The $setOnInsert operator sets the value of the specified field only if an upsert is performed.
//
// Example usage:
//
//	update.SetOnInsert("rating", 5.0).SetOnInsert("is_checked_out", false)
func SetOnInsert(field string, value any) *Updater { return New().SetOnInsert(field, value) }

// The $unset operator removes the specified field(s).
//
// Example usage:
//
//	update.Unset("borrower", "due_date")
func Unset(fields ...string) *Updater { return New().Unset(fields...) }

// The $currentDate operator sets the value of the specified field to the current date and time.
//
// Example usage:
//
//	update.CurrentDate("due_date")
func CurrentDate(field string) *Updater { return New().CurrentDate(field) }

// The $inc operator increments the value of the specified field by the specified amount.
//
// Example usage:
//
//	update.Inc("number_of_pages", 25)
func Inc(field string, amount any) *Updater { return New().Inc(field, amount) }

// The $min operator updates the specified field only if the specified value is less than the existing field value.
//
// Example usage:
//
//	update.Min("rating", 3.9)
func Min(field string, value any) *Updater { return New().Min(field, value) }

// The $max operator updates the specified field only if the specified value is greater than the existing field value.
//
// Example usage:
//
//	update.Max("rating", 3.9)
func Max(field string, value any) *Updater { return New().Max(field, value) }

// The $mul operator multiplies the value of the specified field.
//
// Example usage:
//
//	update.Mul("rating", 1.2)
func Mul(field string, value any) *Updater { return New().Mul(field, value) }

// The $rename operator renames the specified field.
//
// Example usage:
//
//	update.Rename("old_field", "new_field").Rename("other_old_field", "other_new_field")
func Rename(field string, newName string) *Updater { return New().Rename(field, newName) }

// The $addToSet operator adds an item to an array only if the item does not already exist in the array.
//
// Example usage:
//
//	update.AddToSet("genres", "SciFi")
func AddToSet(field string, value any) *Updater { return New().AddToSet(field, value) }

// AddToSetEach combines [AddToSet] and $each to add items to an array if the items do not
// already exist in the array.
//
// Example usage:
//
//	update.AddToSetEach("genres", "SciFi", "Fantasy")
func AddToSetEach(field string, values ...any) *Updater { return New().AddToSetEach(field, values...) }

// The $pop operator removes the first or last item of the array, depending on the value of the operator.
// Use -1 to remove the first item. Use 1 to remove the last item.
//
// Example usage:
//
//	update.Pop("genres", -1) // Removes the first item in the genres array.
func Pop(field string, value int) *Updater { return New().Pop(field, value) }

// The $push operator appends data to the field value. The specified field must be an array or must not yet exist.
//
// If the specified field does not exist, the field is created, and the value is an array containing the pushed items.
//
// Use [PushEach] to append multiple properties. Use [PushEachPosition] to modify the position of the new items in the array.
//
// Example usage:
//
//	update.Push("genres", "SciFi")
func Push(field string, value any) *Updater { return New().Push(field, value) }

// The $push operator with $each modifier appends multiple values to an array field.
//
// Example usage:
//
//	update.PushEach("genres", "SciFi", "Fantasy")
func PushEach(field string, values ...any) *Updater { return New().PushEach(field, values...) }

// The $position operator modifies the $push operator to specify the position in the array to add items.
//
//   - Use a positive position value to count from the start of the array. For example, 2 inserts the items after the first two items in the array.
//   - Use a negative position value to count from the end of the array. For example, -2 inserts the items before the last two items in the array.
//   - Use a position value of 0 to insert items at the start of the array
//
// When you use position, the $each operator is required, even if you want to insert a single item at the specified position.
//
// Example usage:
//
//	update.PushEachPosition("genres", 1, "SciFi", "Fantasy")
func PushEachPosition(field string, position int, values ...any) *Updater {
	return New().PushEachPosition(field, position, values...)
}
