// Copyright DataStax, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-update; DO NOT EDIT.

package update

// The $set operator sets the value of the specified field to the specified value.
func Set(field string, value any) *Updater { return New().Set(field, value) }

// The $unset operator removes the specified field(s).
func Unset(fields ...string) *Updater { return New().Unset(fields...) }

// The $inc operator increments the value of the specified field by the specified amount.
func Inc(field string, amount any) *Updater { return New().Inc(field, amount) }

// The $min operator updates the specified field only if the specified value is less than the existing field value.
func Min(field string, value any) *Updater { return New().Min(field, value) }

// The $max operator updates the specified field only if the specified value is greater than the existing field value.
func Max(field string, value any) *Updater { return New().Max(field, value) }

// The $rename operator renames the specified field.
func Rename(field string, newName string) *Updater { return New().Rename(field, newName) }
