// Copyright IBM Corp.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by gen-options; DO NOT EDIT.
package serdes

import (
	"fmt"
	"math"
	"reflect"
	"strconv"
	"unsafe"
)

const maxUintptr = ^uintptr(0)

func init() {

	kindCodecs[reflect.Int] = codec{intEncoder, intDecoder}

	kindCodecs[reflect.Int8] = codec{int8Encoder, int8Decoder}

	kindCodecs[reflect.Int16] = codec{int16Encoder, int16Decoder}

	kindCodecs[reflect.Int32] = codec{int32Encoder, int32Decoder}

	kindCodecs[reflect.Int64] = codec{int64Encoder, int64Decoder}

	kindCodecs[reflect.Uint] = codec{uintEncoder, uintDecoder}

	kindCodecs[reflect.Uint8] = codec{uint8Encoder, uint8Decoder}

	kindCodecs[reflect.Uint16] = codec{uint16Encoder, uint16Decoder}

	kindCodecs[reflect.Uint32] = codec{uint32Encoder, uint32Decoder}

	kindCodecs[reflect.Uint64] = codec{uint64Encoder, uint64Decoder}

	kindCodecs[reflect.Uintptr] = codec{uintptrEncoder, uintptrDecoder}

	kindCodecs[reflect.Float32] = codec{float32Encoder, float32Decoder}

	kindCodecs[reflect.Float64] = codec{float64Encoder, float64Decoder}

}

func intEncoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int)(p)), 10), nil
}

func intDecoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[int](), err)
	}

	if num < math.MinInt || num > math.MaxInt {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[int](), fmt.Sprintf("number %v", num))
	}

	*(*int)(p) = int(num)
	return src, nil
}

func int8Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int8)(p)), 10), nil
}

func int8Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[int8](), err)
	}

	if num < math.MinInt8 || num > math.MaxInt8 {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[int8](), fmt.Sprintf("number %v", num))
	}

	*(*int8)(p) = int8(num)
	return src, nil
}

func int16Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int16)(p)), 10), nil
}

func int16Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[int16](), err)
	}

	if num < math.MinInt16 || num > math.MaxInt16 {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[int16](), fmt.Sprintf("number %v", num))
	}

	*(*int16)(p) = int16(num)
	return src, nil
}

func int32Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int32)(p)), 10), nil
}

func int32Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[int32](), err)
	}

	if num < math.MinInt32 || num > math.MaxInt32 {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[int32](), fmt.Sprintf("number %v", num))
	}

	*(*int32)(p) = int32(num)
	return src, nil
}

func int64Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendInt(dst, int64(*(*int64)(p)), 10), nil
}

func int64Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseInt(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[int64](), err)
	}

	if num < math.MinInt64 || num > math.MaxInt64 {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[int64](), fmt.Sprintf("number %v", num))
	}

	*(*int64)(p) = int64(num)
	return src, nil
}

func uintEncoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint)(p)), 10), nil
}

func uintDecoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[uint](), err)
	}

	if num < 0 || num > math.MaxUint {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[uint](), fmt.Sprintf("number %v", num))
	}

	*(*uint)(p) = uint(num)
	return src, nil
}

func uint8Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint8)(p)), 10), nil
}

func uint8Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[uint8](), err)
	}

	if num < 0 || num > math.MaxUint8 {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[uint8](), fmt.Sprintf("number %v", num))
	}

	*(*uint8)(p) = uint8(num)
	return src, nil
}

func uint16Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint16)(p)), 10), nil
}

func uint16Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[uint16](), err)
	}

	if num < 0 || num > math.MaxUint16 {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[uint16](), fmt.Sprintf("number %v", num))
	}

	*(*uint16)(p) = uint16(num)
	return src, nil
}

func uint32Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint32)(p)), 10), nil
}

func uint32Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[uint32](), err)
	}

	if num < 0 || num > math.MaxUint32 {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[uint32](), fmt.Sprintf("number %v", num))
	}

	*(*uint32)(p) = uint32(num)
	return src, nil
}

func uint64Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uint64)(p)), 10), nil
}

func uint64Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[uint64](), err)
	}

	if num < 0 || num > math.MaxUint64 {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[uint64](), fmt.Sprintf("number %v", num))
	}

	*(*uint64)(p) = uint64(num)
	return src, nil
}

func uintptrEncoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendUint(dst, uint64(*(*uintptr)(p)), 10), nil
}

func uintptrDecoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseUint(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[uintptr](), err)
	}

	if num < 0 || num > uint64(maxUintptr) {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[uintptr](), fmt.Sprintf("number %v", num))
	}

	*(*uintptr)(p) = uintptr(num)
	return src, nil
}

func float32Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendFloat(dst, float64(*(*float32)(p)), 'g', -1, 32), nil
}

func float32Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseFloat(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[float32](), err)
	}

	if false {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[float32](), fmt.Sprintf("number %v", num))
	}

	*(*float32)(p) = float32(num)
	return src, nil
}

func float64Encoder(_ EncodeCtx, dst []byte, p unsafe.Pointer) ([]byte, error) {
	return strconv.AppendFloat(dst, float64(*(*float64)(p)), 'g', -1, 64), nil
}

func float64Decoder(ctx DecodeCtx, src []byte, p unsafe.Pointer) ([]byte, error) {
	if b, ok := consumeNull(src); ok {
		return b, nil
	}

	src, num, err := parseFloat(ctx, src)
	if err != nil {
		return src, ctx.unmarshalTypeErrorWrap(src, reflect.TypeFor[float64](), err)
	}

	if false {
		return src, ctx.unmarshalValueTypeError(src, reflect.TypeFor[float64](), fmt.Sprintf("number %v", num))
	}

	*(*float64)(p) = float64(num)
	return src, nil
}
