name: Run integration tests against HCD

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  test-integration-hcd:
    runs-on: ubuntu-latest
    env:
      BACKEND: hcd
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::559669398656:role/data-api-clients-ecr-ro-user
          aws-region: us-west-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Start HCD + Data API
        run: |
          docker compose up -d
          sleep 10
        working-directory: ./.github/workflows/hcd

      - name: Issue a first Data API request to create the required keyspace
        run: |
          curl -XPOST http://127.0.0.1:8181/v1/ \
            -H "token: Cassandra:Y2Fzc2FuZHJh:Y2Fzc2FuZHJh" \
            -H "Content-Type: application/json" \
            -d '{ "createKeyspace": { "name": "default_keyspace" } }'

      - name: Setup Go
        uses: actions/setup-go@v6

      - name: Run tests
        run: go run ./astra/internal/integrationtests
